#!/usr/bin/env python3
"""Generate fun-facts-new.json with exactly 500 unique Polish fun facts."""
import json
import re
from pathlib import Path

EXISTING_TEXTS = set()
# Load existing facts from fun-fakty.js to avoid duplicates
js_path = Path(__file__).resolve().parent.parent / "js" / "fun-fakty.js"
if js_path.exists():
    content = js_path.read_text(encoding="utf-8")
    for m in re.finditer(r"text:\s*'((?:\\'|[^'])*)'", content):
        EXISTING_TEXTS.add(m.group(1).replace("\\'", "'"))

FACTS = [
    # === BIAŁKO (70) ===
    {"emoji": "🩸", "tag": "Białko", "text": "Hemoglobina to białko transportujące tlen — każda cząsteczka unosi do 4 cząsteczek O₂ i składa się z 4 łańcuchów polipeptydowych."},
    {"emoji": "🔬", "tag": "Białko", "text": "Enzym pepsyna rozkłada białko w żołądku przy pH 1,5–2,0 — silniejszym niż kwas cytrynowy w soku pomarańczowym."},
    {"emoji": "🧬", "tag": "Białko", "text": "Białko mTOR to „przełącznik” syntezy mięśniowej — leucyna z jedzenia aktywuje ten szlak w ciągu około 30 minut po posiłku."},
    {"emoji": "🦠", "tag": "Białko", "text": "Przeciwciała to białka immunoglobuliny — organizm produkuje miliardy wariantów, by rozpoznać patogeny."},
    {"emoji": "⚙️", "tag": "Białko", "text": "Aminokwas tryptofan to prekursor serotoniny — około 1 g białka jaja dostarcza wystarczającą porcję na syntezę neuroprzekaźnika."},
    {"emoji": "🏗️", "tag": "Białko", "text": "Aktyna i miozyna to białka kurczliwe — podczas skurczu „chwytają się” jak zębatki, skracając włókno mięśniowe."},
    {"emoji": "🌡️", "tag": "Białko", "text": "Białka denaturują się przy wysokiej temperaturze — stąd białko jaja staje się stałe przy smażeniu, ale aminokwasy pozostają strawne."},
    {"emoji": "🐄", "tag": "Białko", "text": "Białko serwatkowe stanowi około 20% białka mleka krowiego — resztę (~80%) tworzy wolno trawiąca się kazeina."},
    {"emoji": "🫘", "tag": "Białko", "text": "Izoflawony soi nie zastępują białka, ale edamame dostarcza około 11 g białka roślinnego na 100 g — kompletnego profilu aminokwasów."},
    {"emoji": "🍤", "tag": "Białko", "text": "Małże mają około 12 g białka na 100 g i są jednym z najbogatszych źródeł cynku w diecie — minerał kluczowy dla syntezy białek."},
    {"emoji": "🧫", "tag": "Białko", "text": "Albumina stanowi około 60% białka osocza krwi — utrzymuje ciśnienie oncotyczne i transportuje hormony oraz leki."},
    {"emoji": "🥩", "tag": "Białko", "text": "Mięso konie ma około 28 g białka na 100 g i jest tradycyjnym składnikiem w wielu kuchniach Azji Centralnej — rzadko spotykane w Polsce."},
    {"emoji": "🌾", "tag": "Białko", "text": "Seitan z glutenu pszennego ma nawet 25 g białka na 100 g — więcej niż tofu, ale nie nadaje się osobom z celiakią."},
    {"emoji": "🐟", "tag": "Białko", "text": "Dorsz ma około 18 g białka i prawie zerowy tłuszcz — dlatego jest bazą w diecie niskokalorycznej na całym świecie."},
    {"emoji": "🥛", "tag": "Białko", "text": "Izolat białka serwatkowego (WPI) ma ponad 90% białka w proszku — prawie bez laktozy i tłuszczu."},
    {"emoji": "🔋", "tag": "Białko", "text": "Białko transferyny w krwi wiąże żelazo i kontroluje jego dostępność — nadmiar wolnego żelaza jest toksyczny dla komórek."},
    {"emoji": "🧪", "tag": "Białko", "text": "Metoda Kjeldahla, opracowana w 1883 roku, przez ponad wiek była złotym standardem pomiaru zawartości białka w żywności."},
    {"emoji": "🍖", "tag": "Białko", "text": "Wołowina chuda ma około 26 g białka i 3 mg żelaza hemu na 100 g — forma żelaza wchłaniana 2–3× lepiej niż z roślin."},
    {"emoji": "🌱", "tag": "Białko", "text": "Konopie jadalne (hamp protein) mają około 33 g białka na 100 g i kompletny profil aminokwasów — rosną w popularności w Europie."},
    {"emoji": "🦗", "tag": "Białko", "text": "Mączka z owadów (np. szarańczy) ma 50–70% białka suchej masy — EFSA zatwierdziła kilka gatunków jako żywność w UE od 2021 roku."},
    {"emoji": "💊", "tag": "Białko", "text": "EAA (aminokwasy egzogenne) to 9 związków, których organizm nie syntetyzuje — muszą pochodzić z diety lub suplementacji."},
    {"emoji": "🧬", "tag": "Białko", "text": "Leucyna stanowi około 8–9% białka mięśniowego — to najsilniejszy aktywator mTOR spośród aminokwasów."},
    {"emoji": "🍳", "tag": "Białko", "text": "Białko jaja kurzego ma biologiczną wartość 100 w starej skali — punkt odniesienia dla oceny innych źródeł białka."},
    {"emoji": "🫙", "tag": "Białko", "text": "Tempeh to sfermentowana soja z grzybem Rhizopus — około 19 g białka na 100 g i łatwiejsze trawienie niż surowa soja."},
    {"emoji": "🐙", "tag": "Białko", "text": "Ośmiornica ma około 30 g białka na 100 g i wysoką zawartość tauryny — aminokwasu wspierającego funkcje serca."},
    {"emoji": "🥣", "tag": "Białko", "text": "Quinoa to pseudozboże z kompletnym białkiem (~14 g/100 g) — Inkowie nazywali ją „matką wszystkich ziaren”."},
    {"emoji": "🔥", "tag": "Białko", "text": "TEF (termiczny efekt pożywienia) białka wynosi około 20–30% jego kalorii — przy węglowodanach to ~5–10%, przy tłuszczach ~0–3%."},
    {"emoji": "🧊", "tag": "Białko", "text": "Białka odpornościowe (IG) w siarce wołowej wspierają układ immunologiczny u sportowców — badania pokazują mniej infekcji górnych dróg oddechowych."},
    {"emoji": "🍗", "tag": "Białko", "text": "Udko kurczaka ma więcej kolagenu i tłuszczu niż pierś, ale też około 26 g białka — smaczniejsze, lekko bardziej kaloryczne."},
    {"emoji": "🌿", "tag": "Białko", "text": "Spirulina to sinica z około 57–65% białka suchej masy — ale porcja łyżeczki to tylko około 4 g białka w praktyce."},
    {"emoji": "🧬", "tag": "Białko", "text": "Białko p53 nazywane „strażnikiem genomu” — mutacje tego genu występują w ponad połowie ludzkich nowotworów."},
    {"emoji": "🥜", "tag": "Białko", "text": "Mąka migdałowa ma około 21 g białka na 100 g — ale też 50 g tłuszczu, więc kaloryczność przekracza 600 kcal."},
    {"emoji": "🐟", "tag": "Białko", "text": "Sardynki w puszce (z ościami) łączą około 25 g białka z wapniem — ości są miękkie i jadalne po przetworzeniu."},
    {"emoji": "⚡", "tag": "Białko", "text": "Hydrolyzat białka serwatkowego trawi się szybciej niż koncentrat — aminokwasy docierają do krwi w ciągu 20–40 minut."},
    {"emoji": "🫘", "tag": "Białko", "text": "Ciecierzyca ma około 8–9 g białka na 100 g gotowanej — hummus to wygodny, ale kaloryczny sposób na roślinne białko."},
    {"emoji": "🧀", "tag": "Białko", "text": "Parmezan dojrzewający ma około 35 g białka na 100 g — jeden z najkoncentrowaniejszych źródeł białka w kuchni."},
    {"emoji": "🌊", "tag": "Białko", "text": "Algi wakame mają białko roślinne plus jod — 100 g suchej wodorosty może pokryć tygodniowe zapotrzebowanie na jod."},
    {"emoji": "🔬", "tag": "Białko", "text": "Białko ryby wędzonej jest strawne jak świeżej — ale proces wędzenia podnosi zawartość sodu nawet 10-krotnie."},
    {"emoji": "🍄", "tag": "Białko", "text": "Pieczarki mają około 3 g białka na 100 g, ale zawierają ergotioneinę — aminokwas o silnych właściwościach antyoksydacyjnych."},
    {"emoji": "🥩", "tag": "Białko", "text": "Białko wołowina + ryż to klasyczny posiłek kulturystów lat 80. — prosty, tani i skuteczny profil aminokwasów."},
    {"emoji": "🧬", "tag": "Białko", "text": "Keratyna to białko fibrylarne włosów i paznokci — zbudowane głównie z aminokwasu cysteiny połączonej mostkami disulfidowymi."},
    {"emoji": "🫛", "tag": "Białko", "text": "Białko grochu w proszku ma neutralny smak i dobrą rozpuszczalność — stąd dominacja grochu w odżywkach roślinnych post-2020."},
    {"emoji": "🐑", "tag": "Białko", "text": "Ser feta ma około 14 g białka i 21 g tłuszczu na 100 g — grecki klasyk, który łączy białko z wapniem."},
    {"emoji": "🧪", "tag": "Białko", "text": "Limit syntezy białek mięśniowych na posiłek to około 20–40 g białka wysokiej jakości u dorosłego — więcej nie „przyspiesza” procesu liniowo."},
    {"emoji": "🌰", "tag": "Białko", "text": "Pestki dyni mają około 30 g białka na 100 g — ale porcja 30 g to realistyczna ilość jako dodatek do sałatki."},
    {"emoji": "🦴", "tag": "Białko", "text": "Rosół z kości zawiera kolagen, glicynę i prolinę — białka wspierające chrząstki, ale nie zastępujące pełnowartościowego białka mięsnego."},
    {"emoji": "🍤", "tag": "Białko", "text": "Langustynki mają około 20 g białka i tylko 1 g tłuszczu na 100 g — delikatniejsze od krewetek, podobny profil odżywczy."},
    {"emoji": "🔋", "tag": "Białko", "text": "Białko C-reaktywne (CRP) rośnie przy stanie zapalnym — dietetycy czasem monitorują je obok markera zdrowia metabolicznego."},
    {"emoji": "🥛", "tag": "Białko", "text": "Kazein micelarny tworzy żel w żołądku — uwalnia aminokwasy przez 6–7 godzin, idealny na nocną regenerację."},
    {"emoji": "🌾", "tag": "Białko", "text": "Owies ma avenina — białko podobne do glutenu, ale zwykle bezpieczne dla większości osób z nietolerancją glutenu (nie celiakią)."},
    {"emoji": "🐟", "tag": "Białko", "text": "Łosoś ma około 20 g białka i 13 g tłuszczu na 100 g — białko plus omega-3 w jednym kawałku."},
    {"emoji": "🧬", "tag": "Białko", "text": "Białka histonowe owijają DNA jak szpula — kontrolują, które geny są „włączone” w danej komórce."},
    {"emoji": "🥩", "tag": "Białko", "text": "Polędwica wołowa ma około 23 g białka i 8 g tłuszczu — jedno z najchudszych mięs czerwonych w sklepie."},
    {"emoji": "🫘", "tag": "Białko", "text": "Fasola czarna ma około 9 g białka i 8 g błonnika na 100 g gotowanej — sytość na długo przy niskim koszcie."},
    {"emoji": "⚗️", "tag": "Białko", "text": "Białko fibrynogenu zamienia się w fibrinę podczas krzepnięcia krwi — kluczowy krok zatrzymywania krwawienia po urazie."},
    {"emoji": "🍳", "tag": "Białko", "text": "Jedno jajo L dostarcza około 6–7 g białka — połowa w białku, połowa w żółtku wraz z luteiną i choliną."},
    {"emoji": "🌱", "tag": "Białko", "text": "Błonnik mleczanowy (wpc) to koncentrat 70–80% białka — tańszy od izolatu, ale z większą ilością laktozy."},
    {"emoji": "🦃", "tag": "Białko", "text": "Mielone mięso z indyka ma około 27 g białka i 8 g tłuszczu — alternatywa dla wołowiny w burgerach na redukcji."},
    {"emoji": "🧫", "tag": "Białko", "text": "Białko receptora insuliny (IR) na powierzchni komórek otwiera „bramkę” dla glukozy — kluczowe po posiłku węglowodanowym."},
    {"emoji": "🥣", "tag": "Białko", "text": "Owsianka na mleku roślinnym z dodatkiem proszku białkowego to prosty sposób na 30+ g białka na śniadanie."},
    {"emoji": "🔬", "tag": "Białko", "text": "Białko z mleka krowiego składa się z około 80% kazeiny i 20% serwatki — proporcja odwrotna do mleka ludzkiego."},
    {"emoji": "🐟", "tag": "Białko", "text": "Pstrąg hodowlany ma około 20 g białka i jest bogaty w witaminę B12 — często niedoceniany w polskiej diecie."},
    {"emoji": "🌿", "tag": "Białko", "text": "Białko konopne zawiera edestynę — albuminę roślinną o wysokiej strawności, podobną do białka jaja."},
    {"emoji": "🧬", "tag": "Białko", "text": "Chaperony białkowe (np. HSP70) pomagają innym białkom zachować prawidłowy kształt — szczególnie aktywne po stresie cieplnym treningu."},
    {"emoji": "🥩", "tag": "Białko", "text": "Wątróbka wołowa ma około 26 g białka i 6 mg żelaza na 100 g — superfood, którego smak trzeba polubić."},
    {"emoji": "🫙", "tag": "Białko", "text": "Skyr to islandzki jogurt o około 11 g białka na 100 g — gęstszy i bardziej białkowy niż zwykły jogurt naturalny."},
    {"emoji": "⚡", "tag": "Białko", "text": "Po głodówce 16:8 synteza białek mięśniowych po pierwszym posiłku jest podwyższona — organizm „nadrabia” zaległości."},
    {"emoji": "🍖", "tag": "Białko", "text": "Szynka serrano ma około 30 g białka na 100 g — suszone mięso koncentruje białko, ale też sód."},
    {"emoji": "🧪", "tag": "Białko", "text": "Białko BCAAs to leucyna, izoleucyna i walina — rozgałęzione aminokwasy metabolizowane głównie w mięśniach, nie w wątrobie."},
{"emoji": "🥚", "tag": "Białko", "text": "Witamina B12 wiąże się z białkiem czynnika Castle'a wydzielanym w żołądku — bez tego białka B12 nie wchłania się z jelit."},

    # === ODCHUDZANIE (70) ===
    {"emoji": "📊", "tag": "Odchudzanie", "text": "1 kg tkanki tłuszczowej to około 7700 kcal — teoretyczna baza do liczenia tempa redukcji, choć w praktyce waga też obejmuje wodę."},
    {"emoji": "🔄", "tag": "Odchudzanie", "text": "Adaptacja metaboliczna podczas długiej diety może obniżyć TDEE o 10–15% — organizm oszczędza energię poza samym spadkiem masy."},
    {"emoji": "🍽️", "tag": "Odchudzanie", "text": "Efekt „last supper” przed dietą — ostatni wielki posiłek psychologicznie oddala start, ale nie wpływa na fizykę kalorii po rozpoczęciu deficytu."},
    {"emoji": "📉", "tag": "Odchudzanie", "text": "Whoosh effect to gwałtowny spadek wagi po tygodniach plateau — prawdopodobnie legitymizacja wody, nie magiczne spalanie tłuszczu."},
    {"emoji": "🧮", "tag": "Odchudzanie", "text": "Wzór Mifflina-St Jeora szacuje BMR z dokładnością ±10% — lepszy punkt startu niż losowe „1200 kcal dla kobiet”."},
    {"emoji": "🍕", "tag": "Odchudzanie", "text": "Flexible dieting (IIFYM) pokazało w badaniach podobne wyniki redukcji co dieta „clean” — liczy się deficyt, nie etykieta produktu."},
    {"emoji": "💪", "tag": "Odchudzanie", "text": "Podczas agresywnej diety trening siłowy zachowuje masę mięśniową — bez niego nawet 25% ubyteku masy może pochodzić z mięśni."},
    {"emoji": "🥤", "tag": "Odchudzanie", "text": "Zero kaloryczne słodziki mogą podtrzymywać apetyt na słodkie — efekt indywidualny, nie reguła dla wszystkich."},
    {"emoji": "📱", "tag": "Odchudzanie", "text": "Badania pokazują, że osoby trackujące jedzenie tracą średnio 2× więcej wagi niż te bez monitoringu — nawet bez formalnej diety."},
    {"emoji": "🌙", "tag": "Odchudzanie", "text": "Jedzenie po 20:00 nie tuczy samo z siebie — ale wieczorne przekąski często są kaloryczne i poza planem (lody, chipsy, alkohol)."},
    {"emoji": "🍞", "tag": "Odchudzanie", "text": "Odwrócenie diety (reverse dieting) po redukcji stopniowo podnosi kalorie o 50–100 tygodniowo — odbudowa metabolizmu bez gwałtownego tycia."},
    {"emoji": "⚖️", "tag": "Odchudzanie", "text": "Waga poranna powinna być trendem tygodniowym, nie pojedynczą liczbą — aplikacje typu Happy Scale uśredniają wahania."},
    {"emoji": "🥗", "tag": "Odchudzanie", "text": "Sałatka z 3 łyżkami oliwy ma 360 kcal samego tłuszczu — „zdrowy” posiłek też wymaga kontroli porcji."},
    {"emoji": "🏃", "tag": "Odchudzanie", "text": "Compensatory eating po cardio — wielu ludzi nieświadomie je więcej po treningu, niż spaliło, unieważniając deficyt."},
    {"emoji": "🧠", "tag": "Odchudzanie", "text": "Ghrelina („hormon głodu”) rośnie podczas redukcji — dlatego apetyt na diecie to biologia, nie brak silnej woli."},
    {"emoji": "📏", "tag": "Odchudzanie", "text": "Stosunek talia/biodra powyżej 0,90 u mężczyzn i 0,85 u kobiet wskazuje na trzewny tłuszcz — niebezpieczniejszy niż tłuszcz podskórny."},
    {"emoji": "🍫", "tag": "Odchudzanie", "text": "Planowanie „cheat day” na sobotę psychologicznie pomaga wytrwać w tygodniu — ale 5000 kcal w jeden dzień może zatrzymać redukcję na tydzień."},
    {"emoji": "💧", "tag": "Odchudzanie", "text": "Retencja wody po wysokosodowym posiłku może dodać 1–3 kg na wadze przez 24–48 h — nie mylić z przyrostem tłuszczu."},
    {"emoji": "🔄", "tag": "Odchudzanie", "text": "Diet break (1–2 tygodnie na maintenance) co 8–12 tygodni redukcji obniża hormon głodu i poprawia adherence w badaniach."},
    {"emoji": "🍳", "tag": "Odchudzanie", "text": "Wysokobiałkowa dieta redukcyjna zwiększa sytość — 30% kalorii z białka vs 15% daje około 400 kcal mniej jedzenia dziennie w eksperymentach."},
    {"emoji": "📉", "tag": "Odchudzanie", "text": "Yo-yo effect (efekt jojo) wiąże się z utratą masy mięśniowej i gorszą kontrolą apetytu — wolniejsza redukcja go minimalizuje."},
    {"emoji": "🥜", "tag": "Odchudzanie", "text": "Orzechy mają wysoką gęstość kaloryczną, ale badania pokazują, że organizm wchłania z nich o 15–20% mniej kalorii niż podaje etykieta."},
    {"emoji": "🕐", "tag": "Odchudzanie", "text": "16:8 IF nie spala więcej tłuszczu niż tradycyjne posiłki przy tym samym deficycie — upraszcza jedynie kontrolę kalorii."},
    {"emoji": "🍺", "tag": "Odchudzanie", "text": "Piwo 500 ml to około 200 kcal — 3 piwa tygodniowo to 600 kcal, czyli prawie 100 g tłuszczu miesięcznie w bilansie."},
    {"emoji": "📊", "tag": "Odchudzanie", "text": "Ubytek 10% masy ciała poprawia markery insulinooporności nawet u osób bez cukrzycy — efekt widoczny w ciągu tygodni."},
    {"emoji": "🍽️", "tag": "Odchudzanie", "text": "Talerz 27 cm vs 32 cm zmniejsza porcję o około 22% bez świadomego ograniczania — iluzja optyczna działa na mózg."},
    {"emoji": "🏋️", "tag": "Odchudzanie", "text": "Recomp (budowa mięśni + utrata tłuszczu jednocześnie) działa głównie u początkujących, osób z nadwagą i po przerwie od treningu."},
    {"emoji": "🧊", "tag": "Odchudzanie", "text": "Brown fat activation przez zimno może zwiększyć wydatek energetyczny o 100–300 kcal/d — efekt realny, ale trudny do utrzymania codziennie."},
    {"emoji": "📱", "tag": "Odchudzanie", "text": "Zdjęcia postępu co 2 tygodnie pokazują zmiany, których waga nie odzwierciedla — woda, cykl menstruacyjny i trening maskują wynik."},
    {"emoji": "🥑", "tag": "Odchudzanie", "text": "Tłuszcz w diecie redukcyjnej powinien wynosić minimum 0,5 g/kg masy ciała — mniej pogarsza wchłanianie witamin A, D, E, K."},
    {"emoji": "🍚", "tag": "Odchudzanie", "text": "Refeed day (wysokie węglowodany, maintenance kalorii) co 7–14 dni podnosi leptynę i leptinę — poprawia samopoczucie na diecie."},
    {"emoji": "💊", "tag": "Odchudzanie", "text": "GLP-1 agoniści (semaglutyd) zmniejszają apetyt o 20–30% — farmakologia redukcji, nie zamiennik nawyków żywieniowych."},
    {"emoji": "🚶", "tag": "Odchudzanie", "text": "10 000 kroków dziennie to około 400–500 kcal u przeciętnej osoby — realny deficyt bez dodatkowego cardio."},
    {"emoji": "🍫", "tag": "Odchudzanie", "text": "Czekolada 85% — 2 kostki (20 g) to około 120 kcal — sposób na słodki craving bez zjedzenia całej tabliczki."},
    {"emoji": "📉", "tag": "Odchudzanie", "text": "Minimalna masa ciała zdrowa (BMI 18,5) to orientacyjna granica — poniżej rośnie ryzyko osteoporozy i zaburzeń hormonalnych."},
    {"emoji": "🥛", "tag": "Odchudzanie", "text": "Mleko pełnotłuste vs odtłuszczone ma podobny efekt redukcji w meta-analizach — liczy się całkowity bilans, nie sam tłuszcz mleczny."},
    {"emoji": "🔄", "tag": "Odchudzanie", "text": "Set point theory sugeruje, że ciało broni wagi ±2–3 kg — długoterminowa zmiana wymaga trwałej zmiany stylu życia, nie 6-tygodniowej diety."},
    {"emoji": "🍽️", "tag": "Odchudzanie", "text": "Restauracja podaje porcje 2–3× większe niż domowe — połowa talerza na wynos to prosta strategia redukcyjna."},
    {"emoji": "🧠", "tag": "Odchudzanie", "text": "Leptyna sygnalizuje sytość z tłuszczu — podczas redukcji jej poziom spada, mózg interpretuje to jako „głód mimo jedzenia”."},
    {"emoji": "📊", "tag": "Odchudzanie", "text": "Skóra po dużej utracie wagi (20+ kg) może wymagać 6–24 miesięcy na retrakcję — wiek i genetyka decydują o efekcie."},
    {"emoji": "🥤", "tag": "Odchudzanie", "text": "Kawa czarna ma 2 kcal — ale latte z syropem to 300+ kcal. Zamiana na americano oszczędza tysiące kcal miesięcznie."},
    {"emoji": "🏃", "tag": "Odchudzanie", "text": "Strefa spalania tłuszczu (60–70% max HR) spala więcej % tłuszczu, ale mniej kalorii łącznie niż trening HIIT."},
    {"emoji": "🍳", "tag": "Odchudzanie", "text": "Białko na śniadaniu (25–30 g) zmniejsza kalorie przy obiedzie o około 150 kcal w badaniach — efekt sytości trwa godzinami."},
    {"emoji": "📉", "tag": "Odchudzanie", "text": "Waga w cyklu menstruacyjnym może wzrosnąć o 1–3 kg w fazie lutealnej — retencja wody, nie regres diety."},
    {"emoji": "🥗", "tag": "Odchudzanie", "text": "Meal prep w niedzielę eliminuje decyzje żywieniowe w tygodniu — mniej impulsywnych zakupów i dostaw jedzenia."},
    {"emoji": "🍞", "tag": "Odchudzanie", "text": "Chleb razowy ma podobne kalorie co biały (~250 kcal/100 g) — przewaga to błonnik i niższy IG, nie magiczna niskokaloryczność."},
    {"emoji": "💪", "tag": "Odchudzanie", "text": "Utrata 0,5 kg mięśni vs 0,5 kg tłuszczu zmienia wygląd sylwetki dramatycznie inaczej — dlatego waga nie mówi całej prawdy."},
    {"emoji": "🧮", "tag": "Odchudzanie", "text": "Aktywność NEAT spada nieświadomie na diecie — mniej gestów, wolniejsze chodzenie. To ukryty „zjadacz” deficytu."},
    {"emoji": "🍫", "tag": "Odchudzanie", "text": "Efekt halo: etykieta „fit”, „bio” lub „protein” sprawia, że jemy większe porcje tego samego produktu."},
    {"emoji": "📱", "tag": "Odchudzanie", "text": "Waga inteligentna z analizą składu ciała (BIA) ma błąd ±3–5% na tłuszcz — trend tygodniowy ma sens, pojedynczy pomiar nie."},
    {"emoji": "🥤", "tag": "Odchudzanie", "text": "Sok „świeżo wyciskany” 250 ml ma 110 kcal i zero błonnika — jabłko zjedzone w całości daje sytość przy 80 kcal."},
    {"emoji": "🔄", "tag": "Odchudzanie", "text": "Minnesota Starvation Experiment (1944) pokazał, że ekstremalny deficyt prowadzi do obsesji na punkcie jedzenia — biologia, nie słabość charakteru."},
    {"emoji": "🍽️", "tag": "Odchudzanie", "text": "Intermittent Energy Restriction (5:2) — 2 dni po 500–600 kcal i 5 dni normalnie — działa tak samo jak codzienny deficyt w meta-analizach."},
    {"emoji": "🏋️", "tag": "Odchudzanie", "text": "Trening na czczo nie spala więcej tłuszczu niż po posiłku przy tym samym deficytu dziennym — kwestia preferencji, nie magii."},
    {"emoji": "📊", "tag": "Odchudzanie", "text": "Redukcja 5% masy ciała poprawia ciśnienie krwi średnio o 5 mmHg — efekt porównywalny z lekką dawką leku."},
    {"emoji": "🥜", "tag": "Odchudzanie", "text": "Dodanie 30 g orzechów do diety redukcyjnej w badaniach nie pogorszyło utraty wagi — sytość zrekompensowała kalorie."},
    {"emoji": "🍺", "tag": "Odchudzanie", "text": "Alkohol hamuje lipolizę na 12–24 h po spożyciu — wątroba priorytetowo metabolizuje etanol zamiast tłuszczu."},
    {"emoji": "📏", "tag": "Odchudzanie", "text": "Klatka piersiowa minus talia (w cm) to prosty wskaźnik sylwetki V — lepszy niż sama waga dla mężczyzn budujących formę."},
    {"emoji": "🧠", "tag": "Odchudzanie", "text": "Decision fatigue — im więcej decyzji w ciągu dnia, tym gorsze wybory żywieniowe wieczorem. Plan posiłków to oszczędność „baterii woli”."},
    {"emoji": "🍳", "tag": "Odchudzanie", "text": "Gotowanie w domu wiąże się ze średnio 200 kcal mniej dziennie niż jedzenie na mieście — kontrola oleju i porcji."},
    {"emoji": "💧", "tag": "Odchudzanie", "text": "Glikogen wiąże 3–4 g wody na gram — po obcięciu węglowodanów waga spada szybko w pierwszych dniach (woda, nie tłuszcz)."},
    {"emoji": "📉", "tag": "Odchudzanie", "text": "Biggest Loser study (2016) wykazał spowolniony metabolizm nawet 6 lat po show — ekstremalne diety mają długoterminowy koszt."},
    {"emoji": "🥗", "tag": "Odchudzanie", "text": "Błonnik 25–35 g/dzień zwiększa sytość i poprawia florę jelitową — oba efekty wspierają utrzymanie deficytu."},
    {"emoji": "🍫", "tag": "Odchudzanie", "text": "Cravings na czekoladę u kobiet w fazie lutealnej wynikają z spadku serotoniny — mały kawałek gorzkiej czekolady może je łagodzić."},
    {"emoji": "🔄", "tag": "Odchudzanie", "text": "Reverse dieting po 12 tygodniach redukcji: +100 kcal co tydzień przez 8 tygodni odbudowuje TDEE bez gwałtownego przyrostu tłuszczu."},
    {"emoji": "📊", "tag": "Odchudzanie", "text": "U 80% osób na redukcji waga stoi co najmniej 2 tygodnie w pewnym momencie — plateau to norma, nie porażka."},
    {"emoji": "🍽️", "tag": "Odchudzanie", "text": "Eating slowly (20 min posiłek) zmniejsza kalorie o około 10% w badaniach — sytość dociera zanim zjesz za dużo."},
    {"emoji": "🏃", "tag": "Odchudzanie", "text": "EPOC po HIIT to dodatkowe 50–200 kcal w ciągu 24 h — realne, ale często przesadnie reklamowane jako „spalanie przez 48 h”."},
    {"emoji": "🧮", "tag": "Odchudzanie", "text": "Deficyt 750 kcal/d daje teoretycznie 0,75 kg/tydzień — ale organizm adaptuje się szybciej niż przy 500 kcal, ryzykując utratę mięśni."},

    # === ODŻYWIANIE (80) ===
    {"emoji": "🥦", "tag": "Odżywianie", "text": "Brokuł ma sulforafan — związek aktywujący enzym detoksykacyjny Nrf2 w wątrobie, szczególnie silny w kwiatkach, nie łodydze."},
    {"emoji": "🫐", "tag": "Odżywianie", "text": "Borówki amerykańskie mają najwyższą zawartość antocyjanów spośród popularnych owoców — około 120 mg na 100 g."},
    {"emoji": "🧄", "tag": "Odżywianie", "text": "Allicyna powstaje dopiero po zmiażdżeniu czosnku — gotowanie ją niszczy, dlatego czosnek dodaje się na końcu smażenia."},
    {"emoji": "🥬", "tag": "Odżywianie", "text": "Jarmuż (kale) ma 705 µg witaminy K1 na 100 g — interakcje z lekami przeciwzakrzepowymi (warfaryna) wymagają stałej porcji."},
    {"emoji": "🍠", "tag": "Odżywianie", "text": "Batat ma IG około 44 po ugotowaniu i schłodzeniu — skrobia retrogradacyjna obniża wpływ na glukozę."},
    {"emoji": "🐟", "tag": "Odżywianie", "text": "Selen w tuńczyku (100 µg/100 g) wspiera deiodinazy — enzymy konwertujące T4 na aktywny hormon tarczycy T3."},
    {"emoji": "🥑", "tag": "Odżywianie", "text": "Awokado ma więcej potasu niż banan (485 vs 358 mg/100 g) — ważne dla ciśnienia krwi i funkcji mięśni."},
    {"emoji": "🌶️", "tag": "Odżywianie", "text": "Kapsaicyna z papryczki chili zwiększa termogenezę o około 50 kcal/d i może lekko tłumić apetyt — efekt umiarkowany."},
    {"emoji": "🍵", "tag": "Odżywianie", "text": "EGCG z zielonej herbaty hamuje COMT — enzym rozkładający katecholaminy, co może wspierać utratę tłuszczu o kilka procent."},
    {"emoji": "🥜", "tag": "Odżywianie", "text": "Migdały mają 21 g białka i 49 g tłuszczu na 100 g — ale badania pokazują, że wchłaniamy z nich mniej kalorii niż podaje etykieta."},
    {"emoji": "🧀", "tag": "Odżywianie", "text": "Ser żółty 30 g dostarcza około 200 mg wapnia — 20% dziennego zapotrzebowania dorosłego człowieka."},
    {"emoji": "🍊", "tag": "Odżywianie", "text": "Grejpfrut zawiera furanokumaryny hamujące CYP3A4 — mogą zwiększać stężenie ponad 85 leków w osoczu. Sprawdź interakcje."},
    {"emoji": "🫒", "tag": "Odżywianie", "text": "Oleokantal z oliwy extra virgin działa podobnie do ibuprofenu na COX — 50 ml oliwy to dawka porównywalna z 1/10 tabletki."},
    {"emoji": "🌾", "tag": "Odżywianie", "text": "Pełnoziarnisty ryż ma 3× więcej magnezu niż biały — minerał zaangażowany w ponad 300 reakcji enzymatycznych."},
    {"emoji": "🥛", "tag": "Odżywianie", "text": "Laktoza to cukier w mleku składający się z glukozy i galaktozy — około 65% dorosłych na świecie ma zmniejszoną tolerancję."},
    {"emoji": "🍄", "tag": "Odżywianie", "text": "Grzyby shiitake mają lentinan — polisacharyd stymulujący układ odpornościowy, badany w kontekście wsparcia onkologicznego."},
    {"emoji": "🥒", "tag": "Odżywianie", "text": "Ogórek kiszony to naturalna probiotyk — Lactobacillus plantarum poprawia florę jelitową lepiej niż wielu suplementów."},
    {"emoji": "🌰", "tag": "Odżywianie", "text": "Nasiona chia po namoczeniu tworzą gel — 10 g błonnika i omega-3 ALA w łyżce, ale wchłanianie ALA to tylko 5–10% konwersji na EPA/DHA."},
    {"emoji": "🍫", "tag": "Odżywianie", "text": "Flavanole kakaowe poprawiają przepływ krwi i obniżają ciśnienie o 2–3 mmHg — wymagają min. 70% kakao i 20 g porcji."},
    {"emoji": "🥕", "tag": "Odżywianie", "text": "Marchewka gotowana z tłuszczem zwiększa wchłanianie beta-karotenu 6-krotnie — karotenoidy są rozpuszczalne w tłuszczach."},
    {"emoji": "🫘", "tag": "Odżywianie", "text": "Fasola biała ma FODMAPy (oligosacharydy) — mogą powodować wzdęcia u osób z IBS, ale mocząc i gotując zmniejszasz je o połowę."},
    {"emoji": "🐟", "tag": "Odżywianie", "text": "Witamina B12 występuje prawie wyłącznie w produktach zwierzęcych — weganie powinni suplementować 250–500 µg dziennie."},
    {"emoji": "🍎", "tag": "Odżywianie", "text": "Pektyna z jabłek wiąże kwasy żółciowe w jelicie — mechanizm obniżania cholesterolu podobny do owsianki."},
    {"emoji": "🧈", "tag": "Odżywianie", "text": "CLA (kwas linolowy sprzężony) w mięsie i nabiale bywa reklamowany jako spalacz — efekt w badaniach to 0,1 kg/miesiąc, marginalny."},
    {"emoji": "🌿", "tag": "Odżywianie", "text": "Rozmaryn zawiera kwas rosmarynowy — silny antyoksydant chroniący tłuszcze przed utlenianiem podczas smażenia mięsa."},
    {"emoji": "🥬", "tag": "Odżywianie", "text": "Szpinak ma oksalany wiążące wapń — gotowanie redukuje je o 30–90%, poprawiając dostępność minerałów."},
    {"emoji": "🍌", "tag": "Odżywianie", "text": "Banany zielone mają skrobię oporną (RS2) — prebiotyk karmiący Bifidobacterium, po dojrzeniu zamienia się w cukier."},
    {"emoji": "🫐", "tag": "Odżywianie", "text": "Acai berry ma ORAC wysoki, ale porcja smoothie to głównie cukier — całe jagody lepsze niż sok czy proszek „superfood”."},
    {"emoji": "🥛", "tag": "Odżywianie", "text": "Kefir ma 10–20 szczepów probiotycznych vs 2–5 w jogurcie — fermentacja 24 h zwiększa zawartość K2 (menachinon)."},
    {"emoji": "🌶️", "tag": "Odżywianie", "text": "Kurkuma zawiera kurkuminę o niskiej biodostępności — pieprz czarny (piperyna) zwiększa wchłanianie nawet 2000%."},
    {"emoji": "🍠", "tag": "Odżywianie", "text": "Ziemniak po ugotowaniu i schłodzeniu ma więcej skrobi opornej — mniejszy wpływ na glukozę przy ponownym podgrzaniu."},
    {"emoji": "🐟", "tag": "Odżywianie", "text": "Ryby z farm mają mniej omega-3 niż dzikie — stosunek omega-6/omega-3 w farmowanym łososiu to około 3:1 vs 1:1 u dzikiego."},
    {"emoji": "🥜", "tag": "Odżywianie", "text": "Fistaszki mają najniższy IG (15) spośród orzechów — luteina i zeaksantyna wspierają zdrowie oczu."},
    {"emoji": "🍵", "tag": "Odżywianie", "text": "Matcha to mielone liście herbaty — jedna filiżanka ma 3× więcej EGCG niż zaparzona zielona herbata w torebce."},
    {"emoji": "🧄", "tag": "Odżywianie", "text": "Czosnek obniża ciśnienie krwi o 7–9 mmHg w meta-analizach — efekt porównywalny z lekkimi lekami hipotensyjnymi."},
    {"emoji": "🥦", "tag": "Odżywianie", "text": "Kalafior ma sulforafan jak brokuł, ale w mniejszej ilości — różowy kalafior ma antocyjany, nie więcej witamin."},
    {"emoji": "🫒", "tag": "Odżywianie", "text": "Dieta śródziemnomorska z oliwą EVOO obniżyła zdarzenia sercowo-naczyniowe o 30% w badaniu PREDIMED (7500 osób, 5 lat)."},
    {"emoji": "🌾", "tag": "Odżywianie", "text": "Komosa ryżowa (quinoa) nie zawiera glutenu, ale często przetwarzana w fabrykach z pszenicą — celiacy powinni szukać certyfikatu."},
    {"emoji": "🍊", "tag": "Odżywianie", "text": "Hesperydyna z pomarańczy wspiera krążenie żylne — 500 mg ekstraktu dziennie zmniejsza obrzęki nóg w badaniach."},
    {"emoji": "🥑", "tag": "Odżywianie", "text": "Awokado zwiększa wchłanianie karotenoidów z sałatki 3–5× — tłuszcz z awokado zastępuje dressing z oliwą."},
    {"emoji": "🍄", "tag": "Odżywianie", "text": "Grzyby wystawione na UV-B syntetyzują witaminę D2 — 100 g pieczarek na słońcu 15 min to około 10 µg (400 IU)."},
    {"emoji": "🥛", "tag": "Odżywianie", "text": "Wapń z wędzonego serka (np. oscypek) jest strawny jak z mleka — ale sód w 100 g przekracza 1500 mg."},
    {"emoji": "🌰", "tag": "Odżywianie", "text": "Orzechy brazylijskie: 1 sztuka (5 g) pokrywa dzienne zapotrzebowanie na selen (55 µg) — więcej niż 3 sztuki może być toksyczne."},
    {"emoji": "🍫", "tag": "Odżywianie", "text": "Teobromina z kakao ma łagodny efekt pobudzający — wzmacnia kofeinę, ale jest bezpieczna dla psów (u nich toksyczna)."},
    {"emoji": "🥕", "tag": "Odżywianie", "text": "Marchewka nie poprawia wzroku w ciemności u osób bez niedoboru — mit z II wojny światowej (kampania RAF)."},
    {"emoji": "🫘", "tag": "Odżywianie", "text": "Edamame to młoda soja — izoflawony (genisteina) mają efekt estrogen-like, kontrowersyjne u raka piersi, ale dane mieszane."},
    {"emoji": "🐟", "tag": "Odżywianie", "text": "Witamina D3 z ryb tłustych (100 g łososia = 600 IU) wspiera wchłanianie wapnia — kluczowa para dla kości."},
    {"emoji": "🍎", "tag": "Odżywianie", "text": "Jabłka z pestkami zawierają amygdalinę — w dużych ilościach uwalnia cyjanek. Kilka pestek nie zaszkodzi, ale nie jedz ich celowo."},
    {"emoji": "🧈", "tag": "Odżywianie", "text": "Masło vs margaryna: masło ma więcej nasyconych kwasów tłuszczowych, margaryna roślinna więcej trans (starsze) lub sterole (nowsze)."},
    {"emoji": "🌿", "tag": "Odżywianie", "text": "Bazylia świeża ma eugenol — związek przeciwzapalny, ale w świeżej formie, nie suszonej (niższe stężenie)."},
    {"emoji": "🥬", "tag": "Odżywianie", "text": "Rukola ma glukozinolany — związki siarkowe z charakterystycznym ostrym smakiem i właściwościami antybakteryjnymi."},
    {"emoji": "🍌", "tag": "Odżywianie", "text": "Potas z banana (358 mg/100 g) reguluje ciśnienie w komórkach — kluczowy przy poceniu i diecie wysokobiałkowej."},
    {"emoji": "🫐", "tag": "Odżywianie", "text": "Zamrożone jagody mają więcej antocyjanów niż świeże po tygodniu w lodówce — mrożenie tuż po zbiorze zatrzymuje degradację."},
    {"emoji": "🥛", "tag": "Odżywianie", "text": "A2 mleko (tylko beta-kazeina A2) bywa lepiej tolerowane przez osoby z „nietolerancją laktozy” — problem może leżeć w kazeinie A1."},
    {"emoji": "🌶️", "tag": "Odżywianie", "text": "Imbir zawiera gingerol — hamuje COX-2 i 5-LOX, co tłumaczy tradycyjne stosowanie przeciw nudnościom i stanom zapalnym."},
    {"emoji": "🍠", "tag": "Odżywianie", "text": "Fioletowy słodki ziemniak (ube) ma antocyjany i więcej błonnika niż pomarańczowy — oba mają podobne kalorie (~86 kcal/100 g)."},
    {"emoji": "🐟", "tag": "Odżywianie", "text": "Mercury (rtęć) kumuluje się w dużych rybach — tuńczyk, miecznik lepiej max 1–2×/tydzień, sardynki i szproty prawie wolne."},
    {"emoji": "🥜", "tag": "Odżywianie", "text": "Masło orzechowe naturalne ma olej na wierzchu — wymaga mieszania, ale bez palmowego oleju stabilizującego jak w tańszych markach."},
    {"emoji": "🍵", "tag": "Odżywianie", "text": "Herbata czarna ma teofilinę — rozszerza oskrzela i ma łagodniejsze pobudzenie niż kawa (mniej kofeiny, więcej L-teaniny)."},
    {"emoji": "🧄", "tag": "Odżywianie", "text": "Czosnek czarny (fermentowany) ma 2× więcej antyoksydantów niż zwykły — słodszy smak, brak ostrego zapachu."},
    {"emoji": "🥦", "tag": "Odżywianie", "text": "Gotowanie brokułów na parze 5 min zachowuje 90% sulforafanu — wrzątek niszczy mirozynazę potrzebną do jego aktywacji."},
    {"emoji": "🫒", "tag": "Odżywianie", "text": "Oliwa traci jakość po 12–18 miesiącach od tłoczenia — przechowywanie w ciemnym, chłodnym miejscu spowalnia utlenianie polifenoli."},
    {"emoji": "🌾", "tag": "Odżywianie", "text": "Płatki ryżowe mają IG 82 — wyższy niż cukier stołowy (65). Na redukcji lepszy basmati lub ryż jaśminowy."},
    {"emoji": "🍊", "tag": "Odżywianie", "text": "Kiwi złote (SunGold) ma 2× więcej witaminy C niż zielone — 161 mg vs 93 mg na 100 g."},
    {"emoji": "🥑", "tag": "Odżywianie", "text": "Awokado dojrzewa po zerwaniu dzięki etylenu — trzymanie z jabłkiem w papierowej torebce przyspiesza proces o 1–2 dni."},
    {"emoji": "🍄", "tag": "Odżywianie", "text": "Reishi (grzyb lakownica) w proszku ma triterpeny — tradycyjna medycyna chińska, ale dowody kliniczne na odporność są ograniczone."},
    {"emoji": "🥛", "tag": "Odżywianie", "text": "Ser halloumi ma wysoki punkt topnienia (~85°C) — nie rozpływa się na patelni, bo wytwarzany z mleka owczego/koziego z większą ilością kazeiny."},
    {"emoji": "🌰", "tag": "Odżywianie", "text": "Laskowe mają najwyższy proanthocyjanidin spośród orzechów — związek poprawiający przepływ krwi w mózgu w badaniach na osoby starsze."},
    {"emoji": "🍫", "tag": "Odżywianie", "text": "Surowe kakao (nibs) ma 300 mg polifenoli na 10 g — gorzka, ale najzdrowsza forma czekolady bez dodanego cukru."},
    {"emoji": "🥕", "tag": "Odżywianie", "text": "Sok marchwiowy 200 ml ma 94 kcal i beta-karoten — ale bez błonnika z pulpy, łatwiej przesadzić z kaloriami vs cała marchew."},
    {"emoji": "🫘", "tag": "Odżywianie", "text": "Boczniaki mają statynę naturalną (lovastatin-like) — mogą wspierać obniżenie cholesterolu, ale porcja grzybów to ułamek dawki leku."},
    {"emoji": "🐟", "tag": "Odżywianie", "text": "Anchois w oliwie to koncentrat omega-3, wapnia i soli — 5 rybki to 200 mg wapnia, ale też 1000 mg sodu."},
    {"emoji": "🍎", "tag": "Odżywianie", "text": "Ocet jabłkowy 15 ml przed posiłkiem obniża glukozę po jedzeniu o 20–30% — efekt kwasu octowego na opóźnienie opróżniania żołądka."},
    {"emoji": "🧈", "tag": "Odżywianie", "text": "Tłuszcz kokosowy ma 50% kwasu laurynowego — średniołańcuchowy, szybciej metabolizowany, ale wciąż nasycony."},
    {"emoji": "🌿", "tag": "Odżywianie", "text": "Mięta pieprzowa zawiera mentol — aktywuje receptor TRPM8 (zimno), co może zmniejszać odczuwanie bólu mięśni po treningu."},
    {"emoji": "🥬", "tag": "Odżywianie", "text": "Kapusta kiszona ma witaminę C i probiotyki — ale 100 g to też 660 mg sodu. Płucz przed jedzeniem."},
    {"emoji": "🍌", "tag": "Odżywianie", "text": "Tryptofan z banana to prekursor melatoniny — 1 banan wieczorem może wspierać sen, choć efekt jest łagodny."},
    {"emoji": "🫐", "tag": "Odżywianie", "text": "Ekstrakt z czarnej porzeczki (CurraNZ) poprawił wydolność tlenową o 11% w badaniu na biegaczy — antocyjany zmniejszają stres oksydacyjny."},
    {"emoji": "🥛", "tag": "Odżywianie", "text": "Ser mozarella di bufala ma więcej wapnia i mniej sodu niż zwykła — 510 mg wapnia i 16 g tłuszczu na 100 g."},
    {"emoji": "🌶️", "tag": "Odżywianie", "text": "Papryka wędzona (pimentón) ma kapsantyna — antyoksydant nadający czerwony kolor, popularny w kuchni hiszpańskiej."},
    {"emoji": "🍠", "tag": "Odżywianie", "text": "Inulina z topinamburu to prebiotyk FOS — 5–10 g dziennie wspiera Bifidobacterium, ale zacznij od 2 g (wzdęcia!)."},
    {"emoji": "🐟", "tag": "Odżywianie", "text": "Witamina A z wątróbki (100 g = 8000 µg RAE) przekracza UL — jedz max 1×/tydzień, zwłaszcza w ciąży (teratogenność)."},
    {"emoji": "🥜", "tag": "Odżywianie", "text": "Tahini (pasta sezamowa) ma 17 g białka i 50 g tłuszczu — bazowy składnik hummusu, kaloryczny, ale pełen wapnia."},
    {"emoji": "🍵", "tag": "Odżywianie", "text": "Rooibos nie ma kofeiny i zawiera aspalathin — antyoksydant unikalny dla rooibosu, badany pod kątem insulinooporności."},
    {"emoji": "🧄", "tag": "Odżywianie", "text": "Suplement czosnkowy (600 mg allicyny) obniżył ciśnienie o 7 mmHg w meta-analizie — porównywalnie z lekką terapią."},
    {"emoji": "🥦", "tag": "Odżywianie", "text": "Szparagi mają asparaginę — aminokwas nadający mocny zapach moczu u 40% ludzi (genetyczna zdolność wyczuwania)."},
    {"emoji": "🫒", "tag": "Odżywianie", "text": "Oliwa z oliwek z pierwszego tłoczenia na zimno (cold pressed) zachowuje więcej polifenoli niż „extra light” rafinowana."},
    {"emoji": "🥭", "tag": "Odżywianie", "text": "Mango jest bogate w witaminę A i C — ale jedna sztuka to też 45 g cukrów, więc porcja kontroluje kalorie."},
    {"emoji": "🥦", "tag": "Odżywianie", "text": "Gorzka czekolada 85% ma mniej węglowodanów niż mleczna i około 11 g błonnika na 100 g — umiarkowana porcja to deser z korzyścią."},
    {"emoji": "🍞", "tag": "Odżywianie", "text": "Chleb na zakwasie ma niższy indeks glikemiczny niż na drożdżach dzięki kwasowi mlekowemu z fermentacji — cukier uwalnia się wolniej."},
    {"emoji": "🥗", "tag": "Odchudzanie", "text": "Białko na redukcji zwiększa uczucie sytości przez hormony PYY i GLP-1 — jedzenie 30 g białka na posiłek ułatwia trzymanie deficytu."},
    {"emoji": "🕐", "tag": "Odchudzanie", "text": "Interwałowy trening 3 razy po 20 minut tygodniowo potrafi dać podobną redukcję tkanki tłuszczowej jak codzienne godzinne cardio."},
    {"emoji": "🛌", "tag": "Odchudzanie", "text": "Chronicznie zbyt krótki sen (poniżej 6 h) podnosi poziom greliny i obniża leptynę — co sprzyja podjadaniu i tyciu nawet bez zmiany diety."},
    {"emoji": "🍟", "tag": "Odchudzanie", "text": "Smażenie w głębokim tłuszczu dodaje produktowi 100-200 kcal na 100 g — pieczenie w air fryerze redukuje to kilkukrotnie."},
    {"emoji": "💡", "tag": "Odchudzanie", "text": "Diety stosowane na własną rękę rzadziej się udają — meta-analizy pokazują wyższą skuteczność przy wsparciu dietetyka i regularnym pomiarze."},
    {"emoji": "🧂", "tag": "Odchudzanie", "text": "Zmniejszenie soli nie spala tłuszczu, ale redukuje retencję wody — na wadze potrafi to dać 1-2 kg mniej w pierwszym tygodniu."},
    {"emoji": "🍽️", "tag": "Odchudzanie", "text": "Wielkość talerza ma znaczenie — jedzenie z mniejszego naczynia zmniejsza porcję średnio o 20-30% bez poczucia niedosytu."},
    {"emoji": "👟", "tag": "Odchudzanie", "text": "NEAT (codzienna aktywność poza treningiem) potrafi różnić ludzi o 300-500 kcal dziennie — chodzenie i wiercenie się też się liczy."},
    {"emoji": "🧠", "tag": "Odchudzanie", "text": "Słowo 'dieta' bywa pułapką — badania sugerują, że trwałe zmiany zamiast restrykcji dają lepsze utrzymanie wagi po 2 latach."},
    {"emoji": "🥒", "tag": "Odchudzanie", "text": "Warzywa objętościowe (sałata, ogórek, brokuły) są niskokaloryczne i wysokoobjętościowe — wypełniają żołądek bez dużego bilansu."},
    {"emoji": "☕", "tag": "Odchudzanie", "text": "Kofeina przed treningiem może zwiększyć spalanie tłuszczu podczas ćwiczeń — efekt najłatwiej zauważyć rano na czczo."},
    {"emoji": "📉", "tag": "Odchudzanie", "text": "Utrata masy nie jest liniowa — naturalne plateau trwające 2-4 tygodnie to norma i nie znak, że dieta przestała działać."},
    # === TRENING ===
    {"emoji": "🏋️", "tag": "Trening", "text": "Progresywne przeciążenie to podstawa budowy mięśni — bez stopniowo rosnącego obciążenia organizm nie ma powodu rosnąć."},
    {"emoji": "🔄", "tag": "Trening", "text": "Mięśnie rosną głównie podczas odpoczynku, nie podczas ćwiczeń — trening to tylko sygnał, regeneracja to budowa."},
    {"emoji": "💪", "tag": "Trening", "text": "Przysiad angażuje pośladki, uda, łydki i korpus — to jedno z najbardziej wielozadaniowych ćwiczeń na całe ciało."},
    {"emoji": "🏃", "tag": "Trening", "text": "Cardio stałe i interwałowe spalają podobnie kalorii — ale HIIT po treningu utrzymuje podwyższone spalanie (EPOC) dłużej."},
    {"emoji": "🦵", "tag": "Trening", "text": "Nogi to największa grupa mięśniowa ciała — ich trening mocno stymuluje wydzielanie testosteronu i hormonu wzrostu."},
    {"emoji": "🧬", "tag": "Trening", "text": "Genetyka wpływa na siłę i rzeźbę, ale większość różnic w sylwetce to trening, dieta i konsekwencja — nie tylko DNA."},
    {"emoji": "🤸", "tag": "Trening", "text": "Rozciąganie statyczne przed ciężkim treningiem może obniżać siłę — lepiej rozgrzać się dynamicznie, a stretch zostawić po."},
    {"emoji": "🎯", "tag": "Trening", "text": "Pompki angażują klatkę, triceps i mięśnie stabilizujące tułów — to ćwiczenie z masą własną, które robi się wszędzie."},
    {"emoji": "⌛", "tag": "Trening", "text": "Trening siłowy 2-3 razy w tygodniu przynosi dużą część efektów co 5 — najważniejsza jest długoterminowa konsekwencja."},
    {"emoji": "🛡️", "tag": "Trening", "text": "Martwy ciąg wzmacnia prostowniki grzbietu i tylny łańcuch — poprawia postawę i odciąża kręgosłup w życiu codziennym."},
    {"emoji": "💓", "tag": "Trening", "text": "Trening oporowy obniża ciśnienie krwi porównywalnie z częścią leków — mięśnie pracujące jak druga pompa wspierają układ krążenia."},
    {"emoji": "📏", "tag": "Trening", "text": "Tempo wykonania powtórzenia ma znaczenie — kontrolowane opuszczanie (negatywy) buduje siłę inaczej niż rzucanie ciężaru."},
    {"emoji": "🌡️", "tag": "Trening", "text": "Rozgrzewka podnosi temperaturę mięśni, co zwiększa elastyczność i zmniejsza ryzyko kontuzji — wystarczy 5-10 minut."},
    {"emoji": "🦾", "tag": "Trening", "text": "Uginanie ramion ze sztangą to klasyk na biceps, ale przysiad i podciąganie budują więcej masy w całym ciele."},
    {"emoji": "🛏️", "tag": "Trening", "text": "Sen to część treningu — 7-9 godzin to często warunek przyrostu siły, bo hormon wzrostu wydziela się głównie w nocy."},
    {"emoji": "🤯", "tag": "Trening", "text": "Trenując do wyczerpania, często tracisz na technice — lepiej 2-3 powtórzenia w zapasie i czysty ruch niż pełne spalenie z błędem."},
    {"emoji": "🍝", "tag": "Trening", "text": "Węglowodany przed treningiem to paliwo jak benzyna przed jazdą — bez nich intensywne ćwiczenia szybciej wyczerpują glikogen."},
    {"emoji": "🖐️", "tag": "Trening", "text": "Chwyt na drążku (dłonie do siebie) zmienia zaangażowanie mięśni — podciąganie szeroko to plecy, wąsko to biceps."},
    {"emoji": "🏛️", "tag": "Trening", "text": "Trening klatki, pleców i nóg w osobne dni to klasyczny split — ale częste trenowanie tej samej grupy ma też zwolenników."},
    {"emoji": "🧠", "tag": "Trening", "text": "Wizualizacja ruchu przed serią może poprawić technikę i aktywację mięśni — część sportowców trenuje też umysłowo."},
    {"emoji": "🔥", "tag": "Trening", "text": "Trening metaboliczny (circuit) łączy siłę z kondycją — krótsze przerwy biją tętno jak cardio, a jednocześnie dają bodziec mięśniowy."},
    {"emoji": "🦶", "tag": "Trening", "text": "Push to wypychanie ciężaru, pull to przyciąganie do ciała — balans tych dwóch wzorców ruchu chroni stawy barkowe."},
    {"emoji": "🏋️‍♂️", "tag": "Trening", "text": "Wolniejsze powtórzenie może dać taki sam bodziec jak większy ciężar, bo mięsień dłużej pracuje pod obciążeniem."},
    {"emoji": "♻️", "tag": "Trening", "text": "Zmiana kąta, tempa czy kolejności ćwiczeń co kilka tygodni łamie stagnację w przyroście siły i motywacji."},
    {"emoji": "🧎", "tag": "Trening", "text": "Deska (plank) nie spala magazynów brzucha, ale buduje wytrzymałość mięśni głębokich ważnych dla zdrowia pleców."},
{"emoji": "🏋️", "tag": "Trening", "text": "Siłownia nie jest jedynym miejscem budowania mięśni — kalistenika (drążki, pompki) wystarcza na bardzo wiele lat postępu."},
    {"emoji": "⏱️", "tag": "Trening", "text": "Przerwa między seriami liczy się jak ciężar — 2-3 minuty dla siły, 30-60 s dla wytrzymałości mięśniowej."},
    {"emoji": "🦴", "tag": "Trening", "text": "Trening siłowy zwiększa gęstość kości — podobnie jak dieta bogata w wapń chroni przed osteoporozą w starszym wieku."},
    {"emoji": "🧗", "tag": "Trening", "text": "Podciąganie na drążku to test względnej siły — osoby szczuplejsze mają w nim naturalną przewagę nad masywniejszymi."},
    {"emoji": "🚴", "tag": "Trening", "text": "Kolarstwo i bieganie wzmacniają głównie dolne partie mięśni — dla pełnej sylwetki warto dołożyć górną część ciała."},
    {"emoji": "🧘", "tag": "Trening", "text": "Mobilność stawów to nie luksus — ograniczony zakres ruchu utrudnia poprawne przysiady i martwe ciągi."},
    {"emoji": "🔁", "tag": "Trening", "text": "Regularność ma większy wpływ na efekty niż perfekcyjny plan robiony raz na miesiąc — powtarzalność buduje postęp."},
    {"emoji": "🍗", "tag": "Trening", "text": "Białko po treningu w pierwszej godzinie jest spokojnie używane — ważniejsze jest łączne dzienne spożycie niż magiczne okno."},
    {"emoji": "🩹", "tag": "Trening", "text": "Ból mięśni (DOMS) pojawia się 24-72 h po treningu i nie jest miarą postępu — częsty u początkujących i przy nowych bodźcach."},
    {"emoji": "🤝", "tag": "Trening", "text": "Trening z partnerem motywuje — osoby ćwiczące w duecie rzadziej opuszczają sesje niż samotnicy."},
    {"emoji": "🎧", "tag": "Trening", "text": "Muzyka w słuchawkach potrafi podnieść wydajność i opóźnić zmęczenie — dobre tempo utworów wspiera rytm powtórzeń."},
    {"emoji": "💧", "tag": "Trening", "text": "Odwodnienie o 2% masy ciała obniża wydolność fizyczną i koncentrację — pij wodę też między seriami."},
    {"emoji": "🍚", "tag": "Trening", "text": "Glikogen zużyty podczas treningu odbudowuje się do 48 godzin — stąd mniejsze zapotrzebowanie na węglowodany w dniu odpoczynku."},
    {"emoji": "🧔", "tag": "Trening", "text": "Mężczyźni naturalnie mają więcej masy mięśniowej i siły dzięki testosteronowi — ale kobiety też regularnie budują mięśnie."},
    {"emoji": "📚", "tag": "Trening", "text": "Początkujący robią postępy nawet na planie ogólnorozwojowym — każda nowa aktywność to dla ciała nowy bodziec."},
    {"emoji": "🧱", "tag": "Trening", "text": "Core to nie tylko brzuch — mięśnie głębokie stabilizują każdą serię; ich słabość skutkuje kontuzjami dolnego odcinka."},
    {"emoji": "🎯", "tag": "Trening", "text": "Skupienie umysłu na pracującym mięśniu (mind-muscle) podnosi jego aktywację — potwierdzają to badania EMG."},
    {"emoji": "💤", "tag": "Trening", "text": "Przetrenowanie objawia się zmęczeniem, spadkiem siły i drażliwością — czasem lepszy plan to tydzień odpoczynku."},
    {"emoji": "🏛️", "tag": "Trening", "text": "Podnoszenie ciężarów olimpijskich rozwija moc (power) — a klasyczna kulturystyka skupia się na wielkości mięśni."},
    {"emoji": "🧑‍🦲", "tag": "Trening", "text": "Duże obciążenia nie niszczą mózgu — ryzyko stanowią raczej błędy techniczne obciążające kręgosłup."},
{"emoji": "🦸", "tag": "Trening", "text": "Stretching po treningu siłowym może zmniejszyć sztywność i przyspieszyć regenerację — byle bez bólu."},
    {"emoji": "🏊", "tag": "Trening", "text": "Pływanie angażuje całe ciało przy niskim obciążeniu stawów — dobre w dni regeneracyjne i przy kontuzjach."},
    {"emoji": "🍱", "tag": "Trening", "text": "Trening na pusty żołądek może spalać więcej tłuszczu, ale obniża wydolność — dla większości lepszy lekki posiłek przed."},
    {"emoji": "🌆", "tag": "Trening", "text": "Trening wieczorny nie psuje snu u większości — kluczowa jest stała pora i higiena przed snem, nie sama godzina."},
    {"emoji": "🦾", "tag": "Trening", "text": "Trening bicepsa 2 razy w tygodniu daje lepsze efekty niż 4 — mięśnie rosną podczas regeneracji między sesjami."},
    {"emoji": "🌀", "tag": "Trening", "text": "Wariacja ćwiczeń (np. przysiad sumo zamiast klasycznego) angażuje te same mięśnie pod innym kątem — urozmaica bodziec."},
    {"emoji": "2️⃣", "tag": "Trening", "text": "2 treningi tygodniowo to absolutne minimum dla utrzymania siły u początkujących — 3-4 dają lepsze tempo postępu."},
    {"emoji": "⚖️", "tag": "Trening", "text": "Balans między treningiem a regeneracją to sztuka — mięśnie rosną w reakcji na obciążenie, a nie mimo zmęczenia."},
    {"emoji": "🧤", "tag": "Trening", "text": "Rękawiczki chronią dłonie, ale pogarszają chwyt — do ciężkich martwych ciągów wielu wybiera taśmę magnetyczną."},
    {"emoji": "🥾", "tag": "Trening", "text": "Buty do biegania nie są idealne do przysiadów — płaska, stabilna podeszwa daje pewniejszą podstawę przy sztandze."},
    {"emoji": "📈", "tag": "Trening", "text": "Dziennik treningowy (nawet w telefonie) zwiększa postępy — bez danych łatwo powtarzać za niskie obciążenia."},
    {"emoji": "🫀", "tag": "Trening", "text": "Regularny trening siłowy obniża spoczynkowe tętno i poprawia profil lipidowy niezależnie od samej utraty wagi."},
    {"emoji": "🫁", "tag": "Trening", "text": "Trening interwałowy podnosi VO2max szybciej niż lekkie cardio — większy pułap tlenowy to większe możliwości wysiłku."},
    {"emoji": "🧩", "tag": "Trening", "text": "Każde ciało odpowiada inaczej na ten sam plan — stąd wartość indywidualnego doboru ćwiczeń do budowy i preferencji."},
    {"emoji": "🌍", "tag": "Trening", "text": "Dynamiczna rozgrzewka (wymachy, skłony) przygotowuje stawy bezpieczniej niż długi statyczny stretch na start."},
    {"emoji": "🛀", "tag": "Trening", "text": "Kąpiel po treningu relaksuje — zimna pomaga w obrzękach po ciężkim wysiłku, ale nie przyspiesza magicznie regeneracji."},
    {"emoji": "🌅", "tag": "Trening", "text": "Poranny trening na czczo nie udowadnia większego spalania tłuszczu u każdego — liczy się całkowity dzienny bilans."},
    {"emoji": "🧑‍🏫", "tag": "Trening", "text": "Dobry trener potrafi skrócić drogę do celu — poprawia technikę i dobiera plan, którego nie znajdziesz w sieci."},
    {"emoji": "🎗️", "tag": "Trening", "text": "Mikrourazy mięśni po treningu są naturalne — przebudowa włókien to podstawa przyrostu masy, byle nie przerodziła się w kontuzję."},
    {"emoji": "🧢", "tag": "Trening", "text": "Sekwencja ćwiczeń ma znaczenie — duże, złożone ruchy (przysiady, martwy) najlepiej robić na początku, gdy siła jest największa."},
    {"emoji": "🕒", "tag": "Trening", "text": "Session RPE (odczuwalny wysiłek) w skali 1-10 pomaga dozować intensywność — 7-8 to zwykle optymalny ciężar treningowy."},
    {"emoji": "🧠", "tag": "Trening", "text": "Spożycie kofeiny przed mięśniowym treningiem poprawia siłę i koncentrację — zwłaszcza u osób, które nie piją jej codziennie."},
    {"emoji": "🦵", "tag": "Trening", "text": "Wykroki bez ciężaru są świetnym startem na nogi — trudniejsze warianty z hantlami rosną razem z postępem."},
    {"emoji": "🖐️", "tag": "Trening", "text": "Tłoczenie sztangi leżąc angażuje triceps, barki i klatkę — nie tylko klatkę piersiową, jak się często myśli."},
    {"emoji": "🔊", "tag": "Trening", "text": "Wydychanie podczas fazy wysiłkowej (np. wypchnięcia) pomaga stabilizować ciśnienie — wstrzymywanie oddechu bywa ryzykowne."},

    # === SUPLEMENTY ===
    {"emoji": "💊", "tag": "Suplementy", "text": "Kreatyna jest najlepiej przebadana pod kątem budowy siły i masy — większość badań potwierdza jej skuteczność u osób trenujących."},
    {"emoji": "☕", "tag": "Suplementy", "text": "Kofeina (3-6 mg/kg masy ciała) przed treningiem poprawia siłę i wytrzymałość — działa najlepiej u osób, które jej nie nadużywają."},
    {"emoji": "🟣", "tag": "Suplementy", "text": "Beta-alanina opóźnia 'pieczenie' mięśni dzięki karnozynie — kwas ten buforuje zakwaszenie podczas intensywnych serii."},
    {"emoji": "🧊", "tag": "Suplementy", "text": "Izolat serwatki ma zwykle ponad 90% białka — ale koncentrat (70-80%) wystarczy większości osób przy niższej cenie."},
{"emoji": "🌿", "tag": "Suplementy", "text": "Kofeina i kreatyna działają u większości, ale suplementów 'spalaczy tłuszczu' nie zastąpi deficyt kaloryczny — żaden proszek nie spali tkanki za Ciebie."},
    {"emoji": "🍋", "tag": "Suplementy", "text": "Witamina D jest często suplementowana, bo jej niedobór bywa powszechny — szczególnie jesienią i zimą przy małej ilości słońca."},
    {"emoji": "🧂", "tag": "Suplementy", "text": "Elektrolity (sód, potas, magnez) tracą się z potem — po intensywnym treningu regeneracja bywa lepsza z uzupełnieniem mineralnym."},
    {"emoji": "🦴", "tag": "Suplementy", "text": "Wapń i witamina K2 współpracują w gospodarce kostnej — sam wapń bywa słabiej wykorzystywany bez wsparcia witaminy."},
    {"emoji": "🛌", "tag": "Suplementy", "text": "Melatonina w małych dawkach (0,5-3 mg) krótko przed snem pomaga przy zmianie strefy czasowej — nie jest panaceum na bezsenność."},
    {"emoji": "🐟", "tag": "Suplementy", "text": "Omega-3 (EPA/DHA) wspiera serce i działa przeciwzapalnie — ale suplement nie zrekompensuje tłustej diety pełnej przemysłowych tłuszczów."},
    {"emoji": "🧠", "tag": "Suplementy", "text": "BCAA przed intensywnym treningiem mogą zmniejszyć zmęczenie — ale pełnowartościowe białko zawiera te aminokwasy taniej."},
    {"emoji": "🌡️", "tag": "Suplementy", "text": "Cynk i magnez są ważne dla regeneracji i testosteronu — suplementacja ma sens głównie przy potwierdzonym niedoborze."},
    {"emoji": "🥤", "tag": "Suplementy", "text": "Kazeina przed snem uwalnia aminokwasy przez kilka godzin — stąd popularność wśród osób chcących podtrzymać regenerację nocą."},
    {"emoji": "⚡", "tag": "Suplementy", "text": "Kreatyna w fazie ładowania nie jest konieczna — równie dobrze działa regularne 3-5 g dziennie, po prostu wolniej dociera do pełnej nasycenia."},
    {"emoji": "🍵", "tag": "Suplementy", "text": "Zielona herbata zawiera katechiny wspierające metabolizm — efekt jest delikatny i znika przy nadmiarze kofeiny."},
    {"emoji": "🧪", "tag": "Suplementy", "text": "Kwas foliowy jest kluczowy przed ciążą dla rozwoju cewy nerwowej — ale w nadmiarze może maskować niedobór B12."},
    {"emoji": "🫀", "tag": "Suplementy", "text": "Imbir i kurkuma działają przeciwzapalnie w dietach sportowców — jednak ich efekt jest subtelny i zależny od dawki."},
    {"emoji": "💪", "tag": "Suplementy", "text": "Kreatyna czterohydratowa jest najtańszą i najskuteczniejszą formą — egzotyczne 'novel' kreatyny są reklamowane, ale nie przebadane tak dobrze."},
    {"emoji": "🧠", "tag": "Suplementy", "text": "L-tirozyna bywa stosowana na poprawę koncentracji przy stresie — dowody są ograniczone, a efekt zależy od sytuacji."},
    {"emoji": "🦵", "tag": "Suplementy", "text": "Siarczan glukozaminy może łagodzić ból stawów u części osób — ale efekt przychodzi po tygodniach, nie po pierwszej dawce."},
    {"emoji": "🍫", "tag": "Suplementy", "text": "Kofeina w gumie do żucia (caffeine gum) wchłania się szybciej niż w kawie — bywa używana tuż przed zawodami."},
    {"emoji": "🛡️", "tag": "Suplementy", "text": "Przeciwutleniacze (witamina C, E) w dużych dawkach po treningu mogą blokować sygnał budowy mięśni — więcej nie znaczy lepiej."},
    {"emoji": "🥚", "tag": "Suplementy", "text": "BCAA (leucyna) bywają reklamowane na łagodzenie zakwasów — ale izolowana suplementacja rzadko przewyższa korzyści normalnego posiłku."},
    {"emoji": "🌰", "tag": "Suplementy", "text": "Tauryna to aminokwas wspierający serce i nawodnienie komórek — wiele napojów energetycznych ją zawiera z dodatkiem kofeiny."},
    {"emoji": "🩸", "tag": "Suplementy", "text": "Żelazo suplementowane na własną rękę bywa groźne — jego nadmiar się kumuluje, więc sensownie jest najpierw zbadać poziom ferrytyny."},
    {"emoji": "🧴", "tag": "Suplementy", "text": "Kolagen nie 'odbudowuje stawów' bezpośrednio — choć badania pokazują umiarkowane korzyści przy chorobach stawów po miesiącach stosowania."},
    {"emoji": "☀️", "tag": "Suplementy", "text": "Witamina K z natury występuje w warzywach liściastych — suplement bywa zbędny, jeśli dieta jest bogata w jarmuż czy szpinak."},
    {"emoji": "💊", "tag": "Suplementy", "text": "Suplementacja nie zastąpi posiłku — żaden proszek nie dorówna pełnowartościowemu białku z jajek, mięsa czy nabiału."},
    {"emoji": "🦠", "tag": "Suplementy", "text": "Probiotyki mogą wspierać układ odpornościowy i trawienie — efekt jest indywidualny i zależy od szczepu bakterii."},
    {"emoji": "🧊", "tag": "Suplementy", "text": "Kofeina działka 200 mg przed długim wysiłkiem jest uznawana za legalny środek poprawiający wydolność dzięki dopadkowi do ośrodkowego układu."},
    {"emoji": "⚗️", "tag": "Suplementy", "text": "Adekwatne nawodnienie to suplement nr 1 — odwodnienie pogarsza wydolność bardziej niż brak jakiegokolwiek proszku."},
    {"emoji": "🥤", "tag": "Suplementy", "text": "Napoje izotoniczne przy długim wysiłku uzupełniają węglowodany i sód — przy krótkim treningu wystarczy woda."},
    {"emoji": "🍯", "tag": "Suplementy", "text": "Miód to naturalna glukoza i fruktoza — świetne szybkie paliwo podczas długiego biegu, choć lepiej nie odżywiać się nim na co dzień."},
    {"emoji": "🌿", "tag": "Suplementy", "text": "Ashwagandha bywa polecana na stres i regenerację — badania pokazują umiarkowane efekty, ale potrzebne są dłuższe próby."},
    {"emoji": "💡", "tag": "Suplementy", "text": "Wybierając suplement, patrz na zawartość aktywnego składnika, nie na nazwę marketową — często marki różnią się głównie ceną."},
    {"emoji": "🧠", "tag": "Suplementy", "text": "Suplementy działają, gdy dieta i sen są na miejscu — bez tego nic nie da skoku formy."},
    {"emoji": "🥤", "tag": "Suplementy", "text": "Cytrulina malate bywa polecana na 'pompę' i wytrzymałość podczas treningu — może zmniejszać odczuwane zmęczenie mięśni."},
    {"emoji": "🧪", "tag": "Suplementy", "text": "Kreatyna nie jest przekleństwem dla nerek przy prawidłowej dawce — problem dotyczy głównie osób z chorymi nerkami."},
    {"emoji": "⏳", "tag": "Suplementy", "text": "Większość suplementów wymaga regularności przez tygodnie, by zobaczyć efekty — pojedyncza dawka rzadko coś zmienia."},
    {"emoji": "🫀", "tag": "Suplementy", "text": "Osobom na diecie wegańskiej zaleca się witaminę B12 w formie metylokobalaminy — forma bywa lepiej przyswajalna."},
    {"emoji": "🌾", "tag": "Suplementy", "text": "Cynk przed snem na pusty żołądek może wywoływać mdłości — bezpieczniej przyjąć go z lekkim posiłkiem."},
    {"emoji": "⚡", "tag": "Suplementy", "text": "Dawka kofeiny powyżej 6 mg/kg zaczyna działać odwrotnie — nerwowość i szybsze męczenie zamiast lepszej formy."},
    {"emoji": "🥗", "tag": "Suplementy", "text": "Witaminy rozpuszczalne w tłuszczach (A, D, E, K) najlepiej wchłaniają się z posiłkiem zawierającym tłuszcz."},
    {"emoji": "🎒", "tag": "Suplementy", "text": "Pakując przenośną apteczkę na wyjazd, warto sprawdzić leki na receptę — suplementy rzadko są niezbędne na 2 dni."},
    {"emoji": "🔬", "tag": "Suplementy", "text": "Suplement 'all-in-one' to zwykle marketing — pojedyncze składniki działają lepiej, gdy są jasno dawkowane."},
    {"emoji": "🍼", "tag": "Suplementy", "text": "Kazeina hydrolizowana trawi się szybciej niż micelarna — hydrolizaty bywają lepsze po treningu."},
    {"emoji": "🦴", "tag": "Suplementy", "text": "Bor (mikroelement) bywa reklamowany na testosteron — dowody są słabe, a niedobór rzadki."},
    {"emoji": "💧", "tag": "Suplementy", "text": "HMB (metabolit leucyny) może wspierać utrzymanie mięśni w pierwszych tygodniach treningu — efekt maleje z czasem."},
    {"emoji": "🧠", "tag": "Suplementy", "text": "Kofeina + L-teanina łączy pobudzenie z uspokojeniem — niektórzy opisują dzięki temu lepsze skupienie niż po samej kawie."},
    {"emoji": "🍓", "tag": "Suplementy", "text": "Antocyjany z jagód działają antyoksydacyjnie — ale w suplemencie tracisz błonnik i witaminy z całych owoców."},
    {"emoji": "🔋", "tag": "Suplementy", "text": "Koenzym Q10 wspiera produkcję energii w mitochondriach — badania pokazują korzyści głównie u osób z niedoborem."},
    {"emoji": "🧾", "tag": "Suplementy", "text": "Wybieraj suplementy z certyfikatem badawczym (np. Informed Sport) — to ochrona przed zanieczyszczeniami."},
    {"emoji": "🌰", "tag": "Suplementy", "text": "Kwas alfa-liponowy pomaga komórkom zużywać glukozę — badania u części osób z insulinoopornością są obiecujące."},
    {"emoji": "🥥", "tag": "Suplementy", "text": "MCT (trójglicerydy średniołańcuchowe) bywają używane w keto-koktajlach jako szybkie paliwo — ale nie są panaceum na spalanie."},
    {"emoji": "🩺", "tag": "Suplementy", "text": "Każdy suplement warto skonsultować przy chorobach przewlekłych — niektóre wchodzą w interakcje z lekami."},
    {"emoji": "🧴", "tag": "Suplementy", "text": "Kolagen w proszku łatwo dodać do jogurtu — dieta bogata w witaminę C wspiera jego syntezę."},
    {"emoji": "☀️", "tag": "Suplementy", "text": "Nadmiar witamin rozpuszczalnych w tłuszczach można magazynować — toksyczność dotyczy głównie A i D przy bardzo wysokich dawkach."},
    {"emoji": "💊", "tag": "Suplementy", "text": "Żaden suplement nie zastąpi zbilansowanej diety — większość redukcji wymaga przede wszystkim odpowiednich kalorii."},
    {"emoji": "🫙", "tag": "Suplementy", "text": "Izolat białka sojowego to kompletne białko roślinne — dobry wybór także dla osób nietolerujących laktozy."},
    {"emoji": "⏲️", "tag": "Suplementy", "text": "Nie ma dowodów, że shake po treningu musi pić się natychmiast — prawie równie ważne jest białko spożywane w ciągu dnia."},
    {"emoji": "🎯", "tag": "Suplementy", "text": "Najlepsze suplementy wspierają, ale nie zastąpią umiaru w kaloriach, snu i regularnego treningu."},
    {"emoji": "🔎", "tag": "Suplementy", "text": "Czytaj etykiety — 'białko roślinne organiczne' może kryć nadmiar cukru, a 'zero tłuszczu' więcej węglowodanów."},
    {"emoji": "✨", "tag": "Suplementy", "text": "Suplementacja ma sens jako uzupełnienie, a nie zamiennik — najpierw dieta, potem dodatki."},
# === CIAŁO ===
    {"emoji": "🧬", "tag": "Ciało", "text": "Ciało dorosłego składa się w około 55-60% z wody — mężczyźni zwykle mają jej nieco więcej niż kobiety."},
    {"emoji": "🦴", "tag": "Ciało", "text": "Szkielet dorosłego to 206 kości, a noworodka nawet 300 — część łączy się w miarę wzrostu."},
    {"emoji": "🧠", "tag": "Ciało", "text": "Mózg zużywa ok. 20% energii spoczynkowej ciała — dlatego głodówki mocno zaburzają koncentrację."},
    {"emoji": "🫀", "tag": "Ciało", "text": "Serce bije średnio ok. 100 000 razy na dobę — za życie przepompowuje setki tysięcy litrów."},
    {"emoji": "🫁", "tag": "Ciało", "text": "Płuca mają powierzchnię ok. 70 m² — mniej więcej rozmiar kortu tenisowego, dzięki pęcherzykom płucnym."},
    {"emoji": "💪", "tag": "Ciało", "text": "Ciało ma ponad 600 mięśni szkieletowych — największy to pośladkowy wielki, a najsilniejszy zwykle żwacz."},
    {"emoji": "🦶", "tag": "Ciało", "text": "Stopa składa się z 26 kości i ponad 100 mięśni, ścięgien i więzadeł — jedna z najbardziej skomplikowanych części ciała."},
    {"emoji": "🤲", "tag": "Ciało", "text": "Skóra to największy narząd — dorosły ma jej ok. 1,5-2 m² i wymienia ją w całości co kilka tygodni."},
    {"emoji": "🩸", "tag": "Ciało", "text": "Ciało dorosłego ma ok. 5 litrów krwi — czerwone krwinki żyją ok. 120 dni i powstają w szpiku kostnym."},
    {"emoji": "🍃", "tag": "Ciało", "text": "Każda komórka ciała potrzebuje tlenu — mitochondria spalają glukozę i tłuszcze na energię ATP."},
    {"emoji": "🥵", "tag": "Ciało", "text": "Pocenie to chłodzenie — gdy termoregulacja zawodzi, ciało przegrzewa się podczas długiego wysiłku."},
    {"emoji": "🧂", "tag": "Ciało", "text": "Pot zawiera sód, potas i magnez — intensywne, długie treningi wymagają elektrolitów, nie tylko wody."},
    {"emoji": "🌙", "tag": "Ciało", "text": "Hormon wzrostu wydziela się najintensywniej podczas głębokiego snu — stąd znaczenie odpoczynku dla regeneracji."},
    {"emoji": "🧠", "tag": "Ciało", "text": "Głód i sytość regulują hormony — grelina budzi apetyt, leptyna sygnałizuje sytość po posiłku."},
    {"emoji": "🦠", "tag": "Ciało", "text": "W jelitach żyje więcej bakterii niż jest komórek ciała — mikrobiota wpływa na trawienie, odporność i nastrój."},
    {"emoji": "🌡️", "tag": "Ciało", "text": "Optymalna temperatura ciała to ok. 36,6°C — wysiłek i stres mogą ją chwilowo podnieść."},
    {"emoji": "💤", "tag": "Ciało", "text": "Mięśnie regenerują się najefektywniej w nocy — niedobór snu obniża tempo syntezy białek mięśniowych."},
    {"emoji": "🦴", "tag": "Ciało", "text": "Szpik kostny produkuje krwinki i limfocyty odpornościowe — układ immunologiczny bywa nazywany fabryką krwi."},
    {"emoji": "🫀", "tag": "Ciało", "text": "Tętno spoczynkowe sportowca wytrzymałościowego potrafi spaść nawet poniżej 45 uderzeń na minutę."},
    {"emoji": "🧑‍⚖️", "tag": "Ciało", "text": "Kwas żołądkowy jest kwaśniejszy niż sok z cytryny — ale śluz chroni żołądek przed samostrawieniem."},
    {"emoji": "🤰", "tag": "Ciało", "text": "Ciało potrafi się adaptować — osoby regularnie trenujące mają gęstsze kości i większe serce niż nieaktywne."},
    {"emoji": "🦕", "tag": "Ciało", "text": "Ścięgna łączą mięśnie z kośćmi i są niezwykle wytrzymałe — wytrzymują ogromne siły przy rozciąganiu."},
    {"emoji": "🩹", "tag": "Ciało", "text": "Wątroba potrafi się regenerować — ale chroniczny nadmiar alkoholu i tłuszczu szkodzi jej bezobjawowo latami."},
    {"emoji": "🍚", "tag": "Ciało", "text": "Ciało magazynuje węglowodany jako glikogen w mięśniach i wątrobie — zapas wystarcza na kilkadziesiąt minut wysiłku."},
    {"emoji": "🛋️", "tag": "Ciało", "text": "Długie siedzenie spowalnia spalanie — nawet godzinny trening nie unieważnia całodniowej bezczynności."},
    {"emoji": "🧠", "tag": "Ciało", "text": "Mięśnie wytwarzają miozynę — białko kurczliwe, które napędza ruch; bez niego serce by nie biło."},
    {"emoji": "🥊", "tag": "Ciało", "text": "Skóra odnawia się co ok. 27-40 dni, a wątroba wymienia komórki co kilka miesięcy — ciało nieustannie się przebudowuje."},
    {"emoji": "🦷", "tag": "Ciało", "text": "Zęby to najtwardsza tkanka ciała — mimo to słodycze i brak higieny psują je szybciej niż większość myśli."},
    {"emoji": "⚡", "tag": "Ciało", "text": "Komórki nerwowe przewodzą impulsy z prędkością do 120 m/s — reakcja na gorący garnek zajmuje ułamek sekundy."},
    {"emoji": "🧘", "tag": "Ciało", "text": "Postawa ciała wpływa na oddech — garbienie ogranicza pracę przepony i ogranicza zapas tlenu podczas wysiłku."},
{"emoji": "🩺", "tag": "Ciało", "text": "Zdrowy dorosły oddycha ok. 12-16 razy na minutę — podczas intensywnego wysiłku liczba ta rośnie wielokrotnie."},
    {"emoji": "💦", "tag": "Ciało", "text": "Nerki filtrują ok. 180 litrów osocza dziennie — oddajemy tylko ułamek jako mocz, reszta wraca do krwi."},
    {"emoji": "🌅", "tag": "Ciało", "text": "Rytm dobowy organizmu reguluje metabolizm — jedzenie o nietypowych porach bywa gorzej trawione."},
    {"emoji": "🦴", "tag": "Ciało", "text": "Kości nie są statyczne — pod obciążeniem zagęszczają się, a bez ruchu rozrzedzają."},
    {"emoji": "🧠", "tag": "Ciało", "text": "Mięśnie działają jak narząd endokrynny — wydzielają miozyny poprawiające metabolizm całego ciała."},
    {"emoji": "🫀", "tag": "Ciało", "text": "Powrót żylny wspierają mięśnie łydek — nazywane 'drugim sercem' przy chodzeniu."},
    {"emoji": "🦾", "tag": "Ciało", "text": "Po 30. roku życia naturalnie tracimy część masy mięśniowej — trening siłowy potrafi to wyraźnie spowolnić."},
    {"emoji": "🌬️", "tag": "Ciało", "text": "Tlen jest transportowany przez hemoglobinę w czerwonych krwinkach — jej poziom spada przy anemii."},
    {"emoji": "🧊", "tag": "Ciało", "text": "Ciało spala energię nawet w spoczynku — podstawowa przemiana materii (BMR) to połowa dziennego zapotrzebowania u wielu osób."},
    {"emoji": "🙆", "tag": "Ciało", "text": "Masaże relaksują, ale nie 'ustawiają' kości na stałe — samodzielna mobilność i rozciąganie mają trwalszy efekt."},
# === HISTORIA ===
    {"emoji": "🏛️", "tag": "Historia", "text": "Trening siłowy nie jest nowoczesnym wynalazkiem — już starożytni Grecy podnosili kamienie i organizowali zawody siłowe."},
    {"emoji": "🎗️", "tag": "Historia", "text": "W starożytnym Rzymie istniały 'gymnasia' przeznaczone do ćwiczeń — siłownie mają więc ponad 2000 lat."},
    {"emoji": "🥇", "tag": "Historia", "text": "Pierwsze nowożytne igrzyska olimpijskie (1896) zawierały podnoszenie ciężarów — sport znany od starożytności."},
    {"emoji": "📜", "tag": "Historia", "text": "Eugene Sandow, urodzony w 1867 roku, jest uważany za 'ojca nowoczesnej kulturystyki' i pierwszego celebrytę siły."},
    {"emoji": "🏆", "tag": "Historia", "text": "Mr. Olympia, najbardziej prestiżowy konkurs kulturystyczny, powstał w 1965 roku dzięki Joe Weiderowi."},
    {"emoji": "💪", "tag": "Historia", "text": "Arnold Schwarzenegger wygrał Mr. Olympia 7 razy — a jego 'Golden Six' stał się legendarnym planem treningowym."},
    {"emoji": "🍼", "tag": "Historia", "text": "Odżywki białkowe w proszku istniały już w XIX wieku — pierwotnie traktowane jako 'mięsna herbata' dla osłabionych."},
    {"emoji": "⚗️", "tag": "Historia", "text": "Kreatyna została odkryta w 1832 roku przez francuskiego chemika — jako suplement sportowy trafiła na rynek dopiero w latach 90. XX w."},
    {"emoji": "🏋️", "tag": "Historia", "text": "Halterofilika jako dyscyplina olimpijska zadebiutowała w 1920 roku — jedna z najstarszych konkurencji siłowych."},
    {"emoji": "🧠", "tag": "Historia", "text": "Pozytywny wpływ treningu na zdrowie opisywano już w tekstach starożytnych lekarzy — np. Hipokratesa i Galena."},
    {"emoji": "📚", "tag": "Historia", "text": "Pierwsze podręczniki kulturystyczne drukowano na początku XX wieku — kształtowały powojenną kulturę 'gym'."},
    {"emoji": "🇺🇸", "tag": "Historia", "text": "Amerykański boom na fitness w latach 70-80 (aerobik Jane Fondy, Gold's Gym) wprowadził sport do popkultury."},
    {"emoji": "🍜", "tag": "Historia", "text": "Dawni samuraje trenowali codziennie — japońska koncepcja 'kaizen' bywa odnoszona do ciągłego doskonalenia w sporcie."},
    {"emoji": "🏟️", "tag": "Historia", "text": "Starożytni gladiatorzy jedli głównie rośliny i zboża — mimo że ich nazwa kojarzy się z ostrzem miecza."},
    {"emoji": "🎬", "tag": "Historia", "text": "Film 'Pumping Iron' (1977) z Arnoldem przyniósł kulturystykę do głównego nurtu — i spopularyzował Mr. Olympia."},
{"emoji": "🍌", "tag": "Historia", "text": "Moda na zbożowe śniadania o wysokiej energii narodziła się w XIX wieku wśród zwolenników zdrowego stylu życia w USA."},
    {"emoji": "🏅", "tag": "Historia", "text": "Pierwsze oficjalne mistrzostwa świata w kulturystyce odbyły się w 1949 roku — na wiele lat przed Mr. Olympia."},
    {"emoji": "🗂️", "tag": "Historia", "text": "Termin 'bodybuilding' upowszechnił się w XIX wieku — po Sandowie stał się synonimem treningu sylwetkowego."},
    {"emoji": "🥛", "tag": "Historia", "text": "Lata 50-60 XX wieku przyniosły pierwszą erę suplementów aminokwasowych — początek przemysłu sport nutrition."},
    {"emoji": "🌐", "tag": "Historia", "text": "Rozwój internetu w latach 90. zdemokratyzował wiedzę treningową — dziś plany dostępne są darmowo dla każdego."},
    {"emoji": "🏃", "tag": "Historia", "text": "Olimpiady starożytne nie miały biegu maratońskiego na start — dystans ten wymyślono na igrzyska 1896."},
    {"emoji": "📏", "tag": "Historia", "text": "Wskaźnik BMI opracował Adolphe Quetelet w 1832 roku — pierwotnie dla badań populacyjnych, nie oceny jednostki."},
    {"emoji": "🧠", "tag": "Historia", "text": "Termin 'kaloria' w odniesieniu do jedzenia spopularyzował się ok. przełomu XIX i XX wieku wraz z badaniami metabolizmu."},
    {"emoji": "🎓", "tag": "Historia", "text": "Pierwsze badania nad strawnością białka prowadzono dla wojska w okresie zimnej wojny."},
    {"emoji": "🥇", "tag": "Historia", "text": "Podnoszenie ciężarów było sportem olimpijskim na starożytnych igrzyskach — znamy zapisy o kamieniu z Olimpii."},
    {"emoji": "🧑‍🎤", "tag": "Historia", "text": "Muzyka treningowa ewoluowała od marszów wojskowych po EDM — rytm bywa tak ważny jak sam plan ćwiczeń."},
    {"emoji": "🍽️", "tag": "Historia", "text": "Lata 80. to era diet niskotłuszczowych — późniejsze badania pokazały, że sam tłuszcz nie był winny tyciu."},
    {"emoji": "🏋️", "tag": "Historia", "text": "Fenomen fitnessu z Instagrama to zjawisko XXI wieku — trening nigdy nie był tak widoczny w mediach."},
    {"emoji": "🕰️", "tag": "Historia", "text": "Historia publicznych siłowni sięga starożytnej Grecji — ćwiczenia uważano tam za obowiązek obywatelski."},
    {"emoji": "🍗", "tag": "Historia", "text": "Pojęcie 'sterydy anaboliczne' spopularyzowało się w latach 50. — wcześniej jego rolą był jedynie przywracanie masy po chorobie."},

    # === REKORDY ===
    {"emoji": "🏋️", "tag": "Rekordy", "text": "Rekord świata w martwym ciągu (bez sprzętu) wynosi ponad 500 kg — wykonał go Hafþór Júlíus Björnsson."},
    {"emoji": "💪", "tag": "Rekordy", "text": "Największy zanotowany 'biceps miłosny' u człowieka miał obwód ponad 60 cm w szczytowej formie."},
    {"emoji": "🏃", "tag": "Rekordy", "text": "Rekord świata w maratonie mężczyzn oscyluje wokół 2 godzin — dystans ok. 42,2 km."},
    {"emoji": "⚡", "tag": "Rekordy", "text": "Najszybszy sprint Usaina Bolta to ok. 9,58 s na 100 m — średnia prędkość bliska 38 km/h."},
    {"emoji": "🦵", "tag": "Rekordy", "text": "Rekord w przysiadzie z obciążeniem (equipped) przekracza 600 kg — z użyciem sprzętu wspierającego."},
    {"emoji": "🏆", "tag": "Rekordy", "text": "Najdłuższy ciągły trening siłowy zanotowany to ponad 24 godziny — rekord Guinnessa w maratonie podnoszenia."},
    {"emoji": "🥇", "tag": "Rekordy", "text": "Najwięcej podciągnięć na drążku w ciągu 24 h sięga tysięcy powtórzeń u zawodowych kalisteników."},
    {"emoji": "🦾", "tag": "Rekordy", "text": "Najcięższy wycisk na ławeczce (equipped) przekracza 350 kg — z pełnym wyposażeniem."},
    {"emoji": "🏋️‍♀️", "tag": "Rekordy", "text": "Rekordy kobiet w trójboju siłowym są rosnące — najlepsze zawodniczki dźwigają ponad 400 kg łącznie."},
    {"emoji": "📈", "tag": "Rekordy", "text": "Najdłuższe serie przysiadów (bez ciężaru) wykonane w godzinę sięgają blisko 1000 powtórzeń."},
    {"emoji": "🧗", "tag": "Rekordy", "text": "Rekord świata w wspinaczce na czas to ok. 5 sekund na trudną ścianę 15 m — prędkość niemal niewyobrażalna."},
    {"emoji": "🏊", "tag": "Rekordy", "text": "Najszybszy kraul mężczyzn na 100 m to ok. 46,9 s w basenie 50 m — rekord świata."},
    {"emoji": "🚴", "tag": "Rekordy", "text": "Największa zanotowana moc chwilowa kolarza torowego osiąga ponad 2 000 W podczas sprintu."},
    {"emoji": "🎯", "tag": "Rekordy", "text": "Rekord w pompkach na klatkę w godzinę to ponad 3 000 powtórzeń — wymaga ogromnej wytrzymałości."},
    {"emoji": "🥤", "tag": "Rekordy", "text": "Największa ilość wypchniętych przysiadów w ciągu doby przekracza kilkadziesiąt tysięcy u ekstremalnych sportowców."},
{"emoji": "🤸", "tag": "Rekordy", "text": "Najdłuższe stanie na rękach to ponad 30 godzin u rekordzisty — wymaga ogromnej stabilizacji."},
    {"emoji": "🏃‍♂️", "tag": "Rekordy", "text": "Rekord 100 km biegu to ok. 6,5 godziny — średnia prędkość ponad 15 km/h przez 6 godzin."},
    {"emoji": "⚽", "tag": "Rekordy", "text": "Cristiano Ronaldo w szczytowej formie potrafił skakać na ponad 70 cm ponad ziemię przy główce."},
    {"emoji": "🏀", "tag": "Rekordy", "text": "LeBron James to jeden z niewielu koszykarzy z ponad 40 000 punktów w NBA — rekord wszechczasów."},
    {"emoji": "🏆", "tag": "Rekordy", "text": "Najdłuższa seria burpees bez przerwy sięga tysięcy powtórzeń w zawodach wytrzymałościowych."},
    {"emoji": "🧗‍♀️", "tag": "Rekordy", "text": "Najszybsze przebycie El Capitan (914 m) wspinaczką to niecałe 2 godziny dla elity freeclimberów."},
    {"emoji": "🌊", "tag": "Rekordy", "text": "Najdłuższy pływany dystans bez przerwy przekracza 100 km na otwartych wodach."},
    {"emoji": "📏", "tag": "Rekordy", "text": "Największa zanotowana masa ciała ciężkowca siłowego przekraczała 400 kg w historii strongmana."},
    {"emoji": "🧎", "tag": "Rekordy", "text": "Najdłuższy plank (deska) trwał ponad 9 godzin u rekordzisty — wytrzymałość mięśni głębokich bywa ekstremalna."},
    {"emoji": "🦵", "tag": "Rekordy", "text": "Rekord świata w wspięciach na palce w ciągu minuty to ponad 80 powtórzeń u kalistenika."},
    {"emoji": "🏃‍♀️", "tag": "Rekordy", "text": "Rekord kobiety w maratonie to mniej niż 2 godziny 15 minut — dystans 42 km w tempie poniżej 3:20/km."},
    {"emoji": "🥤", "tag": "Rekordy", "text": "Największa liczba przysiadów wykonanych w godzinę u mężczyzn przekroczyła 1500 powtórzeń."},
    {"emoji": "🏋️", "tag": "Rekordy", "text": "Rekord prób deadliftu 500 kg wielokrotnie przewijał się w mediach — są to jedne z najbardziej spektakularnych wyczynów świata."},
    {"emoji": "🦾", "tag": "Rekordy", "text": "Rekord w uginaniu ramion z oszustwem technicznym opisywany był na ponad 100 kg — mało kto bije go z czystą techniką."},
    {"emoji": "🥇", "tag": "Rekordy", "text": "Najwięcej złotych medali olimpijskich w podnoszeniu ciężarów u jednego sportowca to 2-3 — sport bywa bezwzględny."},
# === PSYCHOLOGIA ===
    {"emoji": "🧠", "tag": "Psychologia", "text": "Kiedy zaczynasz trenować, Twój mózg uczy się lubić rutynę — nie tylko ciało się zmienia, ale i nawyk."},
    {"emoji": "🎯", "tag": "Psychologia", "text": "Małe, konkretne cele (np. 10 pompek) działają lepiej niż ogólne 'chodź na siłownię' — mózg lubi mierzalność."},
    {"emoji": "📅", "tag": "Psychologia", "text": "Regularność jest na start ważniejsza niż intensywność — nawyk zapisuje się w pamięci, gdy działa powtarzalnie."},
    {"emoji": "😄", "tag": "Psychologia", "text": "Trening uwalnia endorfiny i dopaminę — stąd poprawa nastroju i satysfakcji po ćwiczeniach."},
    {"emoji": "🧑‍🤝‍🧑", "tag": "Psychologia", "text": "Trening z grupą zwiększa zaangażowanie — społeczne zobowiązanie utrzymuje motywację lepiej niż samotny plan."},
    {"emoji": "⏳", "tag": "Psychologia", "text": "Atomowe nawyki działają — 20 minut dziennie ma większe znaczenie niż jednorazowe 2 godziny raz na tydzień."},
    {"emoji": "🪞", "tag": "Psychologia", "text": "Porównywanie się z Instagramem obniża motywację — lepiej śledzić własne postępy niż cudze sylwetki."},
    {"emoji": "🎧", "tag": "Psychologia", "text": "Motywująca playlista przed treningiem podnosi gotowość mentalną i obniża odczuwane zmęczenie."},
    {"emoji": "📝", "tag": "Psychologia", "text": "Dziennik postępów (waga, powtórzenia) daje mocną informację zwrotną — widzialny progres utrzymuje nawyk."},
    {"emoji": "😴", "tag": "Psychologia", "text": "Sen wpływa na motywację — niewyspany mózg łatwiej rezygnuje po pierwszej serii i słabiej kontroluje apetyt."},
    {"emoji": "🚫", "tag": "Psychologia", "text": "Zasada 'zrobię choć 15 minut' ułatwia nawyk — lepiej krótki trening niż pominięcie całego przy braku czasu."},
    {"emoji": "🧘", "tag": "Psychologia", "text": "Stres podnosi kortyzol, który sprzyja odkładaniu tłuszczu wokół brzucha — redukcja stresu wspiera cel sylwetkowy."},
    {"emoji": "🥰", "tag": "Psychologia", "text": "Zadowolenie z małego postępu (o 1 powtórzenie więcej) buduje nawyk — nagroda wzmacnia powtarzanie."},
    {"emoji": "📱", "tag": "Psychologia", "text": "Appki fitness i liczniki kroków zwiększają aktywność — mechanizm grywalizacji działa na większość ludzi."},
    {"emoji": "🧩", "tag": "Psychologia", "text": "Trzymanie butów i stroju przy drzwiach zwiększa szansę, że pójdziesz na trening — środowisko buduje nawyk."},
    {"emoji": "🤔", "tag": "Psychologia", "text": "Ludzie przejadają się częściej na tle stresu niż głodu — emocjonalne jedzenie bywa głównym wrogiem diety."},
    {"emoji": "⏰", "tag": "Psychologia", "text": "Ustalona pora treningu tworzy sygnał do nawyku — mózg oczekuje aktywności o tej samej porze dnia."},
    {"emoji": "🛡️", "tag": "Psychologia", "text": "Perspektywa długoterminowa (0,5 kg tygodniowo) działa lepiej niż obietnica szybkich efektów — rozczarowanie rujnuje trwałość."},
    {"emoji": "🌱", "tag": "Psychologia", "text": "Zdrowe przekąski w zasięgu ręki i słodycze w szafie ułatwiają lepsze wybory bez silnej woli."},
    {"emoji": "💬", "tag": "Psychologia", "text": "Publiczna deklaracja celu podnosi odpowiedzialność — nie chcesz zawieść innych, więc trzymasz się planu."},
# === METABOLIZM ===
    {"emoji": "🔥", "tag": "Metabolizm", "text": "Metabolizm to suma wszystkich reakcji chemicznych ciała przekształcających jedzenie w energię i tkanki."},
    {"emoji": "🧊", "tag": "Metabolizm", "text": "Spoczynkowa przemiana materii (BMR) u dorosłych to zwykle 1200-2000 kcal — zależy od masy, płci i wieku."},
    {"emoji": "💪", "tag": "Metabolizm", "text": "Im więcej masy mięśniowej, tym wyższy metabolizm — mięśnie spalają więcej niż tłuszcz nawet w spoczynku."},
    {"emoji": "🍚", "tag": "Metabolizm", "text": "Termiczny efekt pożywienia (TEF) to koszt trawienia — białko wymaga 20-30% swojej energii."},
    {"emoji": "⚡", "tag": "Metabolizm", "text": "Osoby szczuplejsze mają często naturalnie szybszy metabolizm, ale różnice przy tym samym wzroście bywają niewielkie."},
    {"emoji": "🕐", "tag": "Metabolizm", "text": "Metabolizm nie zwalnia drastycznie po 40-tce — większy wpływ niż wiek mają spadek mięśni i mniejsza aktywność."},
    {"emoji": "🥗", "tag": "Metabolizm", "text": "Białko i błonnik podnoszą termiczny efekt i sytość — posiłki z nimi są lepsze dla utrzymania wagi."},
    {"emoji": "💧", "tag": "Metabolizm", "text": "Odwodnienie spowalnia metabolizm — nawet łagodne odwodnienie obniża spalanie i pogarsza wydolność."},
    {"emoji": "🧊", "tag": "Metabolizm", "text": "Zimne prysznice i brunatna tkanka tłuszczowa to moda — realny wpływ na spalanie jest niewielki w porównaniu z ćwiczeniami."},
    {"emoji": "📉", "tag": "Metabolizm", "text": "Po długiej diecie adaptacja obniża spalanie — dlatego trwała zmiana wygląda jak faza, nie jednorazowy sprint."},
    {"emoji": "🧬", "tag": "Metabolizm", "text": "Geny wyznaczają tendencję, ale styl życia daje kontrolę — trening i dieta odpowiadają za dużą część różnic."},
    {"emoji": "🔄", "tag": "Metabolizm", "text": "Małe i częste jedzenie nie 'rozpędzi' metabolizmu ponad miarę — liczy się całkowity bilans kalorii."},
    {"emoji": "🍭", "tag": "Metabolizm", "text": "Cukier prosty podnosi glikemię szybciej niż błonnikowy posiłek — stabilny cukier trzyma apetyt w ryzach."},
    {"emoji": "🏃", "tag": "Metabolizm", "text": "Trening interwałowy wspomaga wykorzystanie węglowodanów — ale nie unieważnia nadmiaru kalorii."},
    {"emoji": "🧠", "tag": "Metabolizm", "text": "Mózg w spoczynku konsumuje dużo glukozy — dlatego przy głodówce spada koncentracja, choć metabolizm pracuje dalej."},
    {"emoji": "🫀", "tag": "Metabolizm", "text": "Tarczyca reguluje tempo metabolizmu — hipo- i hipertyreoza zmieniają spalanie; diagnoza zawsze wymaga lekarza."},
    {"emoji": "🥦", "tag": "Metabolizm", "text": "Warzywa i białko w każdym posiłku stabilizują glikemię — większa kontrola apetytu przez cały dzień."},
]

# ---------------------------------------------------------------------------
# Build output: exactly 500 unique facts, balanced across categories.
# ---------------------------------------------------------------------------

# Target per-category counts (sums to 500)
CATEGORY_LIMITS = {
    "Białko": 70,
    "Odżywianie": 90,
    "Odchudzanie": 80,
    "Trening": 70,
    "Suplementy": 60,
    "Ciało": 40,
    "Historia": 30,
    "Rekordy": 30,
    "Psychologia": 20,
    "Metabolizm": 10,
}


def clean_text(s: str) -> str:
    """Normalize text for duplicate detection."""
    return re.sub(r"[^a-ząćęłńóśźż0-9]+", "", s.lower())


def main() -> None:
    # De-duplicate within the source list (keep first occurrence).
    seen = set()
    unique_facts = []
    for fact in FACTS:
        key = clean_text(fact["text"])
        if key in seen:
            continue
        seen.add(key)
        # Also skip facts that already exist in fun-fakty.js
        if key in EXISTING_TEXTS_NORM:
            continue
        unique_facts.append(fact)

    # Balance per category down to the target limit.
    counts: dict[str, int] = {}
    balanced = []
    for fact in unique_facts:
        tag = fact["tag"]
        counts[tag] = counts.get(tag, 0)
        if counts[tag] < CATEGORY_LIMITS.get(tag, 0):
            balanced.append(fact)
            counts[tag] += 1

    total = len(balanced)
    print(f"Generated {total} fun facts.")
    if total != 500:
        print("WARNING: expected 500, got", total)

    out = Path(__file__).resolve().parent.parent / "fun-facts-new.json"
    out.write_text(json.dumps(balanced, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {out}")


# Normalized set of existing texts from fun-fakty.js
EXISTING_TEXTS_NORM = {clean_text(t) for t in EXISTING_TEXTS}

if __name__ == "__main__":
    main()
